<?php 
	$page = "about-us";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>INSTITUTION AND PROCEDURE :: THE PROVINCIAL PROTECTOR OF CITIZENS - OMBUDSMAN</title>
	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="The Provincial Protector of Citizens - Ombudsman is an independent and autonomous body of the AP Vojvodina that shall protect the rights of citizens and monitor the work of the provincial administrative authorities, public enterprises and institutions which have administrative and public competences and which were founded by the AP Vojvodina, as regards their actions in enacting the decisions and other legal acts of the AP Vojvodina." />

	<link rel="shortcut icon" href="../sr/images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUD3htZ3Nz_OHmAUygmFand6GDGrYu_vU&extension=.js"></script> 
	<script src="https://cdn.mapkit.io/v1/infobox.js"></script> 
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"> 
	<link href="https://cdn.mapkit.io/v1/infobox.css" rel="stylesheet" >

	<link rel="stylesheet" type="text/css" href="../sr/css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="../sr/css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="../sr/css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="../sr/css/style.css" media="screen">

	
	<script type="text/javascript" src="../sr/js/jquery.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.migrate.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="../sr/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.appear.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="../sr/js/bootstrap.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="../sr/js/plugins-scroll.js"></script>
	<script type="text/javascript" src="../sr/js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="../sr/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="../sr/js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="../sr/js/script.js"></script>
	<script type="text/javascript" src="../sr/js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="../sr/js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "INSTITUTION AND PROCEDURE :: The Provincial Protector of Citizens - Ombudsman",
	  "image" : "http://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo-en.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Bulevar Mihajla Pupina 25",
	    "addressLocality" : "Novi Sad",
	    "addressCountry" : "Serbia"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/en/institution-and-procedure.php"
	}
	</script>

</head>
<body>

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="../sr/index.php"><span class="CyrLatIgnore" title="Serbian language">SRB</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include_en/logo-baner.php'; ?>
				<?php include 'include_en/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			<div class="section-content page-banner-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="podvuci">
								<div class="pristupacnost">
									Font size:
								</div>
								<div class="resizer">
									<!-- Koriscena Jquery skripta postavljena u fajl script.js -->
									<a href="#" class="fontSizeMinus" title="Decrease font" style="color: #000; font-size: 0.7em; cursor: pointer;">A</a> 
									<a class="fontReset" title="Reset font" style="color: #000; cursor: pointer;">А</a> 
									<a href="#" class="fontSizePlus" title="Increase font" style="color: #000; font-size: 1.2em; cursor: pointer;">А</a>
								</div>
								<div>
									<img src="" alt="">
								</div>
							</div>
						</div>
						
					</div>
				</div>
			</div>

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-8">
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="sta-je-ombudsman">What is the Ombudsman?</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">The Ombudsman is an institution introduced in 1809 by the Swedish Parliament with an aim to controlling the executive authorities. The term “ombudsman” in Swedish language denotes a person who “has an ear for the voice of the people”. The task of the first Ombudsman was to prevent the King and Government from ignoring the laws. The first Ombudsman relied on their authority to request from administrative authorities to provide reports on the law enforcement, as well as the authority to institute certain proceedings aimed at establishing the responsibility of administrative public servants.</p>
										<p class="fontaccess">The Provincial  Protector of Citizens – Ombudsman is an autonomous and independent authority of the AP Vojvodina in charge of protecting the rights of citizens and monitoring the work of provincial administrative authorities, public enterprises and institutions with administrative and public powers, founded by the AP Vojvodina, concerning their acting in implementation of decisions and other legal acts of the AP Vojvodina.</p>
										<p class="fontaccess">Pursuant to the new Provincial Assembly Decision on the Provincial Protector of Citizens – Ombudsman, the Provincial  Protector of Citizens - Ombudsman shall have four deputies, of whom one shall be elected for the following areas: national minority rights, rights of the child and gender equality.</p>
										<p class="fontaccess">The Decision on Establishing the Institution of the Provincial Ombudsman was adopted  in December 2002.  The first Ombudsman of Vojvodina was elected on 24 September 2003 and their work commenced in January 2004. The institution is based in Novi Sad.</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="nadleznosti">Competences of the Provincial Protector of Citizens – Ombudsman</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">With an aim to protect human rights, the Provincial Protector of Citizens - Ombudsman shall receive and assess the petitions pertaining to violation of human rights, supervise the enforcement of regulations, control the legality, expediency and effectiveness of actions of administrative authorities and shall investigate their work. Furthermore, the Ombudsman shall monitor the enforcement of international standards in the field of human rights, collect information about the enforcement of laws and other regulations in the field of human rights, prepare the annual report on the exercise of human rights, inform the competent authorities and wider public about the violation of human rights, initiate the instigation of criminal, disciplinary or other proceedings with competent authorities in the event of human rights violation etc.</p>
										<p class="fontaccess">The main principles of the Ombudsman’s work shall be legality, impartiality, independence and righteousness.</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="ko-moze-da-se-obrati">Who may contact the Provincial Protector of Citizens - Ombudsman</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Any person who believes any of their human rights has been violated in an act or action by an administrative authority may contact the Ombudsman.</p>
										<p class="fontaccess">Also an heir, guardian or legal representative of the person whose right has been violated may contact the Ombudsman.</p>
										<p class="fontaccess">This could also be done by a non-governmental organisation, citizens’ association or other organisation, on behalf of the person who believes their human rights have been violated, providing a written authorisation.</p>
										<p class="fontaccess">Even persons deprived of liberty are entitled to file a complaint in a sealed envelope, whereas the employees of institutions where persons deprived of liberty are confined, are obliged to submit the complaint of the person deprived of liberty to the Ombudsman, without previously opening or retaining it.</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="postupak">Proceedings of the Provincial Protector of Citizens - Ombudsman</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Following a citizen’s complaint (filed in person, via regular or electronic mail), if acting upon complaints belongs to the scope of competences of the Provincial Protector of Citizens - Ombudsman, providing the complaint was filed within the period of one year of the occurrence of violation or irregularity or enactment of the last act in the disputed matter, the Provincial Protector of Citizens - Ombudsman shall act upon that complaint.  The Provincial Protector of Citizens - Ombudsman shall inform the person who filed the complaint and the administrative authority whose work is the subject of the complaint about instituting the proceedings and request the administrative authority to respond to allegations of the complaint.</p>
										<p class="fontaccess">If requested so by the person who filed the complaint, the Ombudsman shall be obliged to keep the client’s personal data confidential.</p>
										<p class="fontaccess">During the inquiry proceedings, the Ombudsman may summon for an interview and take oral or written depositions and require additional clarifications from all persons employed with administrative authorities, the person who filed the complaint, witnesses, experts and other citizens who have some information on the circumstances of the case. The Ombudsman shall be entitled to request all data and information from the administrative authority, as well as a direct inspection of files, documents and collection of data available at these authorities, including state, official, trade and professional secrets. The Ombudsman shall have a free access to all premises in which administrative authorities carry out their activities and shall be able at any time and without prior announcement, to visit any healthcare institution providing mandatory psychiatric treatment.</p>
										<p class="fontaccess">The Ombudsman shall decide on terminating the proceedings if it is established at the end of the inquiry, that  no violation of human rights or irregular acting by authorities had occurred, or if it is found that the administrative authority whose work was the subject of the complaint, had already eliminated the violation of human rights  during the inquiry. The person who filed the complaint and administrative authority whose work was the subject of the complaint shall be notified of the termination of the proceedings.</p>
										<p class="fontaccess">Should the Ombudsman find, following the completion of the inquiry, that particular human right was violated or certain irregularity in the work occurred, the Ombudsman shall give an opinion, make a proposal or recommendation to the given administrative authority on the ways to eliminate the irregularity or its consequences. The Ombudsman shall also notify the person who filed the petition on the recommendation made.</p>
										<p class="fontaccess">The administrative authorities to which the Ombudsman has forwarded their opinion, proposal or made a recommendation, shall be obliged to notify the Ombudsman within 15 days on the measures undertaken.</p>
										<p class="fontaccess">In addition to action upon complaints of persons who claim their human rights had been violated in an act or activity of an administrative authority, the Provincial Protector of Citizens - Ombudsman may also, exceptionally, act at their own initiative, based on the provided information and other sources, should they conclude that there probably is or was a case of violation of human rights by an administrative authority.</p>
									</div>
								</div>
								<!-- <div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="nema-pomoci">When we are unable to help you</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Када је грађанину потребна правна помоћ у виду састављања поднесака или заступања (пред судом или неким од органа управе), јер за то су надлежне службе бесплатне правне помоћи при општинским/градским управама и адвокати.</p>
										<p class="fontaccess">Када су незадовољни радом органа правосуђа (према Уставу судство је независно и ниједан орган није овлашћен да контролише рад судова и тужилаштава).</p>
										<p class="fontaccess">Када имају притужби на рад послодавца и проблеме радноправне природе (грађанин треба да поднесе пријаву инспекцији рада).</p>
										<p class="fontaccess">Када имају проблема са другим грађанима.</p>
									</div>
								</div> -->
							</div>
							<div class="col-md-4">
								<div class="sidebar right-menu triggerAnimation animated" data-animate="fadeInRight">
									<div class="module-right-menu">
										<ul>
											<li><a class="taraba" href="#sta-je-ombudsman">What is the Ombudsman</a></li>
											<li><a class="taraba" href="#nadleznosti" target="_blank">Competences</a></li>
											<li><a class="taraba" href="#ko-moze-da-se-obrati" target="_blank">Who may contact</a></li>
											<li><a class="taraba" href="#postupak" target="_blank">Proceeding</a></li>
											<!-- <li><a class="taraba" href="#nema-pomoci" target="_blank">Када вам не можемо помоћи</a></li> -->

										</ul>
									</div>
									<div class="col-md-12 sidebar-social-resize resize-add">
										<div class="vest-social a2a_kit a2a_kit_size_32 a2a_default_style">
											<ul class="social-list">
												<li><a class="a2a_button_facebook" href="#"><i class="fa fa-facebook-official hvr-grow"></i></a></li>
												<li><a class="a2a_button_twitter" href="#"><i class="fa fa-twitter-square hvr-grow"></i></a></li>
												<li><a class="a2a_button_google_gmail" href="#"><i class="fa fa-envelope-square hvr-grow"></i></a></li>
											</ul>
											<ul class="font-sizer">
												<li><a href="#" class="fontSizeMinus" title="Decrease font" style="color: #000; cursor: pointer;">A-</a></li>
												<li><a class="fontReset" title="Reset font" style="color: #000; cursor: pointer;">А</a></li>
												<li><a href="#" class="fontSizePlus" title="Increase font" style="color: #000; cursor: pointer;">А+</a></li>
											</ul>
										</div>
										<script async src="https://static.addtoany.com/menu/page.js"></script>
									</div>							
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include_en/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include_en/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="../sr/js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script>

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>



</body>

</html>