<?php 
	$page = "let-us-know";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>Покрајински заштитник грађана - омбудсман</title>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="The Provincial Protector of Citizens - Ombudsman is an independent and autonomous body of the AP Vojvodina that shall protect the rights of citizens and monitor the work of the provincial administrative authorities, public enterprises and institutions which have administrative and public competences and which were founded by the AP Vojvodina (hereinafter: Administrative authorities), as regards their actions in enacting the decisions and other legal acts of the AP Vojvodina." />

	<link rel="shortcut icon" href="../sr/images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="../sr/css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="../sr/css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="../sr/css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="../sr/css/style.css" media="screen">

	
	<script type="text/javascript" src="../sr/js/jquery.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.migrate.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="../sr/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.appear.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="../sr/js/bootstrap.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="../sr/js/plugins-scroll.js"></script>
	<script type="text/javascript" src="../sr/js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="../sr/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="../sr/js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="../sr/js/script.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "LET US KNOW :: The Provincial Protector of Citizens - Ombudsman ",
	  "image" : "http://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo-en.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Bulevar Mihajla Pupina 25",
	    "addressLocality" : "Novi Sad",
	    "addressCountry" : "Serbia"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/en/let-us-know.php"
	}
	</script>

</head>
<body>

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="../sr/index.php"><span class="CyrLatIgnore" title="Serbian language">SRB</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include_en/logo-baner.php'; ?>
				<?php include 'include_en/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			<div class="section-content page-banner-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="podvuci">
								<div class="pristupacnost">
									Font size:
								</div>
								<div class="resizer">
									<!-- Koriscena Jquery skripta postavljena u fajl script.js -->
									<a href="#" class="fontSizeMinus" title="Decrease font" style="color: #000; font-size: 0.7em; cursor: pointer;">A</a> 
									<a class="fontReset" title="Reset font" style="color: #000; cursor: pointer;">А</a> 
									<a href="#" class="fontSizePlus" title="Increase font" style="color: #000; font-size: 1.2em; cursor: pointer;">А</a>
								</div>
								<div>
									<img src="" alt="">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-8">
								<div class="deo-teksta">
									<div class="naglasen-text-box">
										<p class="fontaccess">
											You may contact the Provincial Protector of Citizens - Ombudsman in person, by phone, through an on-line form, regular mail or e-mail. A complaint is filed to the Provincial Protector of Citizens - Ombudsman, which is  the basis for opening one’s dossier, under a particular number. The dossier is used as the basis for further proceedings, i.e. for conducting an inquiry.
										</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="tabovi">

										<ul class="nav nav-tabs">
										  	<li class="active"><a data-toggle="tab" href="#licno"><i class="fa fa-user"></i>In person</a></li>
										  	<li><a data-toggle="tab" href="#telefonom"><i class="fa fa-phone"></i>By phone</a></li>
											<li><a data-toggle="tab" href="#postom"><i class="fa fa-envelope"></i>Write to us</a></li>
										  	<li><a data-toggle="tab" href="#onlajn"><i class="fa fa-check-square-o"></i>Online form</a></li>
										  	<li><a data-toggle="tab" href="#imejl"><i class="fa fa-at"></i>Email</a></li>
										</ul>

										<div class="tab-content">
										  	<div id="licno" class="tab-pane fade in active">
										    	<div>
													<div class="row tab-sadrzaj">
														<div class="col-md-6">
															<h2>File a complaint in person!</h2><p class="fontaccess">25 Mihajla Pupina Blvd, Novi Sad<br>The building of PE “Vode Vojvodine” (DTD building)<br>Ground floor - left wing, Office no. 4<br><br>Every working day, without prior scheduling, from 8.00 AM to 4.00 PM</p>
														</div>
														<div class="col-md-6">
															<div id="map"></div>
														</div>
													</div>
												</div>
											</div>
										  

										  	<div id="telefonom" class="tab-pane fade">
										    	<div>
													<div class="row tab-sadrzaj">
														<div class="col-md-12">
															<h2>Call us on the phone!</h2>
															<p class="fontaccess">Every working day, from 8.00 AM to 4.00 PM, you may call the following telephone numbers:</p>
															<h4><i class="fa fa-phone"></i>+38121/487-41-44<br><i class="fa fa-phone"></i>+38121/55-77-27<br></h4>
														</div>
													</div>
												</div>
										  	</div>
										  	<div id="postom" class="tab-pane fade">
										    	<div>
													<div class="row tab-sadrzaj">
														<div class="col-md-12">
															<h2>Write to us!</h2>
															<p class="fontaccess">You may send your complaints in any form or using <a href="#">the form </a>we have provided.</p> <p class="fontaccess">Our address is as follows:</p><p class="left-border-red-thin fontaccess">Provincial  Protector of Citizens - Ombudsman<br>25 Mihajla Pupina Blvd.<br>21101 Novi Sad</p>
														</div>
													</div>
												</div>
										  	</div>
										  	<div id="onlajn" class="tab-pane fade">
											    <div>
													<div class="row tab-sadrzaj">
														<div class="col-md-12">
															<h2>Fill out an on-line form!</h2>
															<p class="fontaccess">Your complaint is forwarded directly to our electronic mail. Complaints are processed in order of their receipt, regardless of the manner of their submission.</p>
															<a class="linkbtn hvr-sweep-to-right" href="https://goo.gl/forms/Dry7eNzlpeTnV9B72" target="_blank">ONLINE FORM</a>
														</div>
													</div>
												</div>
										  	</div>
										  	<div id="imejl" class="tab-pane fade">
											    <div>
													<div class="row tab-sadrzaj">
														<div class="col-md-12">
															<h2>Send your complaint by electronic mail!</h2>
															<p class="fontaccess">Complaints and attachments may be sent via electronic mail to our e-mail address: <span class="CyrLatIgnore" style="color: #ec155a">predstavke@ombudsmanapv.org</span>. <br>Complaints are processed in order of their receipt, regardless of the manner of their submission.</p>
														</div>
													</div>
												</div>
										  	</div>
										</div>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2>Proceedings of the Provincial Protector of Citizens - Ombudsman</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Following a citizen’s complaint (filed in person, via regular or electronic mail), if acting upon complaints belongs to the scope of competences of the Provincial Protector of Citizens - Ombudsman, providing the complaint was filed within the period of one year of the occurrence of violation or irregularity or enactment of the last act in the disputed matter, the Provincial Protector of Citizens - Ombudsman shall act upon that complaint.  The Provincial Protector of Citizens - Ombudsman shall inform the person who filed the complaint and the administrative authority whose work is the subject of the complaint about instituting the proceedings and request the administrative authority to respond to allegations of the complaint.</p>
										<p class="fontaccess">If requested so by the person who filed the complaint, the Ombudsman shall be obliged to keep the client’s personal data confidential.</p>
										<p class="fontaccess">During the inquiry proceedings, the Ombudsman may summon for an interview and take oral or written depositions and require additional clarifications from all persons employed with administrative authorities, the person who filed the complaint, witnesses, experts and other citizens who have some information on the circumstances of the case. The Ombudsman shall be entitled to request all data and information from the administrative authority, as well as a direct inspection of files, documents and collection of data available at these authorities, including state, official, trade and professional secrets. The Ombudsman shall have a free access to all premises in which administrative authorities carry out their activities and shall be able at any time and without prior announcement, to visit any healthcare institution providing mandatory psychiatric treatment.</p>
										<p class="fontaccess">The Ombudsman shall decide on terminating the proceedings if it is established at the end of the inquiry, that  no violation of human rights or irregular acting by authorities had occurred, or if it is found that the administrative authority whose work was the subject of the complaint, had already eliminated the violation of human rights  during the inquiry. The person who filed the complaint and administrative authority whose work was the subject of the complaint shall be notified of the termination of the proceedings.</p>
										<p class="fontaccess">Should the Ombudsman find, following the completion of the inquiry, that particular human right was violated or certain irregularity in the work occurred, the Ombudsman shall give an opinion, make a proposal or recommendation to the given administrative authority on the ways to eliminate the irregularity or its consequences. The Ombudsman shall also notify the person who filed the petition on the recommendation made.</p>
										<p class="fontaccess">The administrative authorities to which the Ombudsman has forwarded their opinion, proposal or made a recommendation, shall be obliged to notify the Ombudsman within 15 days on the measures undertaken.</p>
										<p class="fontaccess">In addition to action upon complaints of persons who claim their human rights had been violated in an act or activity of an administrative authority, the Provincial Protector of Citizens - Ombudsman may also, exceptionally, act at their own initiative, based on the provided information and other sources, should they conclude that there probably is or was a case of violation of human rights by an administrative authority.</p>
									</div>
								</div>															
							</div>
							<div class="col-md-4">

								
								<div class="sidebar right-documents triggerAnimation animated" data-animate="fadeInRight">
									<div class="module-right-documents">
										<div class="naslov-documents">
											DOWNLOAD A FORM
										</div>
										<div class="images-documents">
											<div class="image1">
												<a href="#"><img class="hvr-grow" src="../sr/images/sidebar/docx.png" alt="Microsoft Word Icon"></a>
											</div>
											<div class="image2">
												<a href="#"><img class="hvr-grow" src="../sr/images/sidebar/pdf.png" alt="Adobe PDF Icon"></a>
											</div>
										</div>																					
									</div>
									<div class="link-right" style="margin-top: 15px;">
										<ul>
											<li><a href="institution-and-procedure.php">About the Ombudsman and complaint proceedings</a></li>	
										</ul>
									</div>
								</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include_en/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include_en/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="../sr/js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<!-- <script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script> -->

	<!-- <script>
		$.CyrLatConverter('L2C');
	</script> -->

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>

<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<!-- <script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script> -->

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCH69OL6vjpkKbseiOwQ7P1AmFv-KBq0iU"></script>
<script src="../sr/js/map.js"></script>


</body>

</html>