<?php 
	$page = "documents";
?>

<!doctype html>

<html lang="sr" class="no-js">

<head>
	
	<title>REPORTS :: THE PROVINCIAL PROTECTOR OF CITIZENS - OMBUDSMAN</title>
	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="The Provincial Protector of Citizens - Ombudsman is an independent and autonomous body of the AP Vojvodina that shall protect the rights of citizens and monitor the work of the provincial administrative authorities, public enterprises and institutions which have administrative and public competences and which were founded by the AP Vojvodina, as regards their actions in enacting the decisions and other legal acts of the AP Vojvodina." />

	<link rel="shortcut icon" href="../sr/images/favicon.ico" type="image/x-icon">

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="../sr/css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="../sr/css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="../sr/css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="../sr/css/style.css" media="screen">

	
	<script type="text/javascript" src="../sr/js/jquery.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.migrate.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="../sr/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.appear.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="../sr/js/bootstrap.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="../sr/js/plugins-scroll.js"></script>
	<script type="text/javascript" src="../sr/js/waypoint.min.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "REPORTS :: The Provincial Protector of Citizens - Ombudsman",
	  "image" : "http://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo-en.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Bulevar Mihajla Pupina 25",
	    "addressLocality" : "Novi Sad",
	    "addressCountry" : "Serbia"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/en/reports.php"
	}
	</script>

</head>
<body>

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="../sr/index.php"><span class="CyrLatIgnore" title="Serbian language">SRB</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include_en/logo-baner.php'; ?>
				<?php include 'include_en/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-8">
								<div class="row akt">
									<div class="akt-naziv">
										<h3 class="akt-naziv-header">ANNUAL REPORTS</h3>
									</div>
								</div>
								<div class="row akt">
									<div class="akt-linija">
										<h3 class="akt-linija-header"></h3>
									</div>
								</div>
								<div class="row informator">
									<div class="informator-tekst">
										<p>The annual report is a document submitted every year by the Provincial Protector of Citizens - Ombudsman to the AP Vojvodina Assembly. The report is forwarded to the AP Vojvodina Assembly by 31 March of the current year, and covers the previous calendar year. The content of the report, time frame for its preparation and forwarding to the AP Vojvodina Assembly, as well as its mandatory publication in the public are regulated in Article 21 of the Provincial Assembly Decision on the Provincial Protector of Citizens - Ombudsman.</p>
										<p>Upon request of the Provincial Protector of Citizens - Ombudsman, the annual report is put on the agenda and discussed in one of the AP Vojvodina Assembly sessions. Based on the Assembly discussion of the Annual Report of the Provincial Protector of Citizens - Ombudsman, the AP Vojvodina Assembly may make certain conclusions. It is important to note that the Assembly neither adopts nor approves of the Annual Report of the Provincial Protector of Citizens - Ombudsman, as it is a document by an independent provincial institution in which this institution gives its opinion of the state of play in the field of human rights on the AP Vojvodina for a particular year.</p>
									</div>
								</div>
								<div class="naslov-upitnici">
									<span>Annual Reports</span>									
								</div>
								<div class="download-upitnici">
									<ul>
										<li><a href="../sr/doc/dokumenti/izvestaji/Godisnji_izvestaj_PZG-ombudsmana_2017-online.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2017</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/Godisnji_izvestaj_PZG-ombudsmana_2016.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2016</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/Godisnji_izvestaj_PZG-ombudsmana_2015.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2015</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/Godisnji_izvestaj_PZG_2014.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2014</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/Godisnji izvestaj_2013.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2013</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/Izvestaj Pokrajinskog ombudsmana za 2012.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2012</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/Izvestaj_PO_2011_Final_001.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2011</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2010.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2010</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2009.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2009</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2008.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2008</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2007.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2007</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2006.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2006</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2005.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2005</a></li>
										<li><a href="../sr/doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2004.pdf" target="_blank">The Annual Report of the Provincial Protector of Citizens - Ombudsman for 2004</a></li>
									</ul>
								</div>
							</div>
							<div class="col-md-4">								
								<div class="sidebar right-documents">
									<div class="najnovije-vesti-right">
										<div class="col-md-12 najnovije-vesti-modul">
											<div class="najnovije-vesti-naslov">
												<span>DOCUMENTS</span>
											</div>
											<div class="najnovije-vesti-links">
												<ul class="najnovije-vesti-lista">
													<li><a href="act.php">Founding Act</a></li>
													<li class="active"><a class="isdisabled" href="reports.php">Reports</a></li>
													<li><a href="information-booklet.php">Information booklet</a></li>
												</ul>
											</div>
										</div>
										<div class="col-md-12 sidebar-social-resize">
											<div class="vest-social a2a_kit a2a_kit_size_32 a2a_default_style">
												<ul class="social-list">
													<li><a class="a2a_button_facebook" href="#"><i class="fa fa-facebook-official hvr-grow"></i></a></li>
													<li><a class="a2a_button_twitter" href="#"><i class="fa fa-twitter-square hvr-grow"></i></a></li>
													<li><a class="a2a_button_google_gmail" href="#"><i class="fa fa-envelope-square hvr-grow"></i></a></li>
												</ul>
												<ul class="font-sizer">
													<li><a href="#" class="fontSizeMinus" title="Decrease font" style="color: #000; cursor: pointer;">A-</a></li>
													<li><a class="fontReset" title="Reset font" style="color: #000; cursor: pointer;">А</a></li>
													<li><a href="#" class="fontSizePlus" title="Increase font" style="color: #000; cursor: pointer;">А+</a></li>
												</ul>
											</div>
											<script async src="https://static.addtoany.com/menu/page.js"></script>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include_en/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include_en/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="../sr/js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

<!-- Skripta koja po ucitavanju stranice dodaje elementu .single-vest-content p klasu fontaccess. Ovo se radi zato sto bi u suprotnom korisnik koji unoisi vest morao sam ya svaki paragraf dodavati ovu klasu. SKRIPTA script.js se PRESELILA IZ HEADERA ISPOD OVE SKRIPTE JER SE U NJOJ NALAZI KOD ZA SMANJIVANJE I POVECAVANJE FONTOVA U PARAGRAFU SA KLASOM FONTACCESS. Prvo mora da se doda klasa a tek onda da se izvrsi skripta za resize fontova.-->
<script>
	$(document).ready(function() {
	  $('.single-vest-content p').addClass('fontaccess');
	});
</script>


<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .vest a. Ovo se radi yato sto jenemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.sve-vesti-vest a').addClass('sve-vesti-slika');
	});
</script>

<script type="text/javascript" src="../sr/js/script.js"></script>

<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<!-- <script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script> -->


</body>

</html>