<?php 
	$page = "home";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>THE PROVINCIAL PROTECTOR OF CITIZENS - OMBUDSMAN</title>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="The Provincial Protector of Citizens - Ombudsman is an independent and autonomous body of the AP Vojvodina that shall protect the rights of citizens and monitor the work of the provincial administrative authorities, public enterprises and institutions which have administrative and public competences and which were founded by the AP Vojvodina (hereinafter: Administrative authorities), as regards their actions in enacting the decisions and other legal acts of the AP Vojvodina." />

	<link rel="shortcut icon" href="../sr/images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUD3htZ3Nz_OHmAUygmFand6GDGrYu_vU&extension=.js"></script> 
	<script src="https://cdn.mapkit.io/v1/infobox.js"></script> 
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"> 
	<link href="https://cdn.mapkit.io/v1/infobox.css" rel="stylesheet" >

	<link rel="stylesheet" type="text/css" href="../sr/css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="../sr/css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="../sr/css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="../sr/css/style.css" media="screen">

	
	<script type="text/javascript" src="../sr/js/jquery.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.migrate.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="../sr/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.appear.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="../sr/js/bootstrap.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="../sr/js/plugins-scroll.js"></script>
	<script type="text/javascript" src="../sr/js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="../sr/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="../sr/js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="../sr/js/script.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "The Provincial Protector of Citizens - Ombudsman ",
	  "image" : "http://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo-en.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Bulevar Mihajla Pupina 25",
	    "addressLocality" : "Novi Sad",
	    "addressCountry" : "Serbia"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/en/index.php"
	}
	</script>

</head>
<body>

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- JavaScriptSDK za Facebook -->
	<div id="fb-root"></div>
	<script>
		(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0&appId=134142830009100&autoLogAppEvents=1';
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>

	<!-- Tab sa strane ciji link vodi ka B2B stranici  -->
	<div id="side-tab">
	  <a class="b2b" onmouseover="changeb2b(this)" onmouseout="normalb2b(this)" target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSeFZpArObbVv7yML33si_OjTKcIiAF5sk3YAZWmL4BVmn5XUQ/viewform?usp=sf_link"></a>
	</div>

	<!-- kraja taba  -->

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="../sr/index.php"><span class="CyrLatIgnore" title="Serbian language">SRB</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include_en/logo-baner.php'; ?>
				<?php include 'include_en/meni.php'; ?>
			</nav>
		</header>
		<!-- End Header -->

		<!-- slider 
			================================================== -->
		<div id="slider" class="slider1">
			<!--
			#################################
				- THEMEPUNCH BANNER -
			#################################
			-->
			
			<div class="tp-banner-container">
				<div class="tp-banner" >
					<ul>
						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="../sr/upload/slide/odluka-slider.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="20% 30%" data-bgrepeat="no-repeat">
							<div class="slika-effect1"></div>
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="140"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="font-size: 40px; z-index: 4; min-width: 500px; max-width: 500px; white-space: inherit; line-height: 50px;">ABOUT THE INSTITUTION AND PROCEDURE
							</div>
							
							<!-- LAYER NR. 2 -->
							<div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div>
							
							<!-- LAYER NR. 3 -->
							<div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="institution-and-procedure.php" class="btn btn-primary">READ MORE</a>
							</div>

							
						</li>

						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="../sr/upload/slide/odluka-slider.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="20% 30%" data-bgrepeat="no-repeat">
							<div class="slika-effect1"></div>
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="140"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4; min-width: 500px; max-width: 500px; white-space: inherit; line-height: 55px;">OMBUDSMAN AND DEPUTY OMBUDSMAN
							</div>
							
							<!-- LAYER NR. 2 -->
							<div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div>
							
							<!-- LAYER NR. 3 -->
							<div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="ombudsman-and-deputies.php" class="btn btn-primary">SEE MORE</a>
							</div>

							
						</li>	


						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/01b.jpg"  alt="slidebg1b"  data-bgfit="cover" data-bgposition="0% 50%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Vredi li života?
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div> -->
							
							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="vredi-li-zivota.php" class="btn btn-primary">Saznajte više</a>
							</div> -->

							
						</li>
						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/02.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="0% 30%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout text-center"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Kiša menja sve!
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">Prilagodi vožnju vremenskim prilikama. 
							</div> -->

							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="340"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="kisa-menja-sve.php" class="btn btn-primary">Pročitajte više</a>
							</div> -->

							
						</li>
						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/03.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="O% 30%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Kad pijem ne vozim!
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">Koliko te košta sledeće piće? 
							</div> -->

							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="340"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="kad-pijem-ne-vozim.php" class="btn btn-primary">Saznajte više</a>
							</div> -->

							
						</li>
					</ul>
					<div class="tp-bannertimer"></div>
				</div>
			</div>
		</div>
		<!-- End slider -->

		<!-- content 
			================================================== -->
		<div class="naslovna-content" id="content">


			<!-- vesti i sidebar
				================================================== -->
			<div class="section-content services-section">

				<div class="services-box1">
					<div class="container">
						<div class="row">

							<div class="col-md-9">
								<div class="article-box">
									<div class="row">
										<div class="col-md-12 naslovna-text">
											<div class="article-content triggerAnimation animated" data-animate="fadeInLeft">
												<h1>What is the Ombudsman?</h1>
												<p>The Ombudsman is an institution introduced in 1809 by the Swedish Parliament with an aim to controlling the executive authorities. The term “ombudsman” in Swedish language denotes a person who “has an ear for the voice of the people”. The task of the first Ombudsman was to prevent the King and Government from ignoring the laws. The first Ombudsman relied on their authority to request from administrative authorities to provide reports on the law enforcement, as well as the authority to institute certain proceedings aimed at establishing the responsibility of administrative public servants.</p>
												<p>The Provincial  Protector of Citizens – Ombudsman is an autonomous and independent authority of the AP Vojvodina in charge of protecting the rights of citizens and monitoring the work of provincial administrative authorities, public enterprises and institutions with administrative and public powers, founded by the AP Vojvodina, concerning their acting in implementation of decisions and other legal acts of the AP Vojvodina.</p>
												<a href="institution-and-procedure.php" class="button-two">Learn more</a>
											</div>
										</div>
									</div>
								</div>
								<div class="article-box">
									<div class="row">
										<div class="col-md-12 naslovna-text">
											<div class="article-content triggerAnimation animated" data-animate="fadeInLeft">
												<h1>Contact us</h1>
												<p>You may contact the Provincial Protector of Citizens - Ombudsman in person, by phone, through an on-line form, regular mail or e-mail. A complaint is filled to the Provincial Protector of Citizens - Ombudsman, which is  the basis for opening one’s dossier, under a particular number. The dossier is used as the basis for further proceedings, i.e. for conducting an inquiry.</p>
												<a href="let-us-know.php" class="button-two">Contact us</a>
											</div>
										</div>
									</div>
								</div>
								<div class="article-box">
									<div class="row">
										<div class="col-md-12 naslovna-text">
											<div class="article-content triggerAnimation animated" data-animate="fadeInLeft">
												<h1>Who we are</h1>
												<p>The Provincial  Protector of Citizens - Ombudsman is elected by the Assembly of Autonomous Province of Vojvodina, by a two-third majority vote out of the total number of deputies, whereas the Ombudsman deputies are elected by a simple majority vote out of the total number of deputies, upon the Ombudsman’s proposal. Candidates for the Ombudsman may be proposed by at least 30 deputies or the Assembly Committee responsible for issues related to organisation and work of the administration.  The Ombudsman's term of office is six years. He/she may be elected to the same office twice in succession, at the most.</p>
												<p>The Provincial Ombudsman has four deputies, three of whom are specialised and elected for the field national minority rights, rights of the child and gender equality, whereas one deputy is responsible for the field of general competences.  At least one of the deputies is elected from among the less represented gender and people belonging to national minorities. The Ombudsman deputy’s  term of office is six years. He/she may be elected to the same office twice in succession, at the most.</p>
												<a href="ombudsman-and-deputies.php" class="button-two">Read more</a>
											</div>
										</div>
									</div>
								</div>
								<div class="article-box">
									<div class="row">
										<div class="col-md-12 naslovna-text">
											<div class="article-content triggerAnimation animated" data-animate="fadeInLeft">
												<h1>Where we are</h1>
												<p>The Provincial  Protector of Citizens - Ombudsman is based in Novi Sad, with the head office located at 25 Mihajla Pupina Blvd. The offices are located in the left wing on the ground floor of the building belonging to the public water management enterprise “Vode Vojvodine”, or commonly known as the “DTD” building. Visits are not scheduled in advance and citizens are allowed to visit us at any time during our working hours.</p>
												<a href="contact.php" class="button-two">Contact us</a>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-3 sidebar-border">
								<aside class="sidebar-advanced">

									<div class="photo-stream">

										<div class="gallery">
											<a href="ombudsman-i-zamenici.php"><img class="hvr-shrink" src="../sr/images/naslovna/Dragana-Coric-250x250.jpg" alt="Ombudsman"/></a>
										</div>
										<h3>Dragana Ćorić, PhD <br><div class="funkcija">Provincial  Protector of Citizens - Ombudsman</div></h3>
									</div>

									<div class="company-info">

										<h2>File a complaint</h2>

										<p>You may contact us in person, by phone, through an on-line form, regular mail or e-mail.</p>

										<div class="social-buttons">

											<a data-popup-open="popup-1" href="#"><i class="fa fa-user hvr-float"></i></a>
											<a data-popup-open="popup-2" href="#"><i class="fa fa-phone hvr-float"></i></a>
											<a data-popup-open="popup-3" href="#"><i class="fa fa-check-square-o hvr-float"></i></a>
											<a data-popup-open="popup-4" href="#"><i class="fa fa-envelope hvr-float"></i></a>
											<a data-popup-open="popup-5" href="#"><i class="fa fa-at hvr-float"></i></a>


										</div>

									</div>

									<div class="radno-vreme">

										<h3>Working hours</h3>
										<p style="font-weight: bold">Mon-Fri: 8AM - 4PM</p>
										<p>25 Mihajla Pupina Blvd.<br>The building of PE “Vode Vojvodine” (DTD building)<br>21101 Novi Sad</p>
										<p><i class="fa fa-phone"></i>+38121/487-41-44<br><i class="fa fa-phone"></i>+38121/55-77-27<br><i class="fa fa-fax"></i>+38121/487-41-44</p>
										<p style="padding-right: 10px;" class="CyrLatIgnore"><i class="fa fa-envelope-o "></i>office@ombudsmanapv.org</p>										

									</div>

									<!-- <div class="our-newsletter">

										<h3><i class="fas fa-chart-line"></i> Our newsletter</h3>

										<form>
											<p>Subscribe to our awesome newsletter!</p>
											<input type="email" name="email" placeholder="email@example.com"/>
											<button>Subscribe</button>
										</form>

									</div>

									<div class="photo-stream">

										<h3><i class="fa fa-picture-o"></i> Photo stream</h3>

										<div class="gallery">
											<a href="#"><img src="assets/images/spice.jpg" alt="Spice"/></a>
											<a href="#"><img src="assets/images/sahale-wa.jpg" alt="Sahale-wa"/></a>

											<p class="pagination">
												<span>2 of 43</span>
												<a href="#" class="previous"></a>
												<a href="#" class="next"></a>
											</p>
										</div>
									</div> -->

								</aside>
							</div>			
						</div>
					</div>
				</div>
			
			<!-- YouTube and Facebook section ========================================================================= -->
			<?php include 'include_en/youtube-social-section.php'; ?>	

			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include_en/linkovi-1-section.php'; ?>

		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include_en/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- POPUP nevidljivi prozori -->

	<div class="popup" data-popup="popup-1" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div>
				<div class="popup-tekst"><h2>File a complaint in person!</h2><p>25 Mihajla Pupina Blvd, Novi Sad<br>The building of PE “Vode Vojvodine” (DTD building)<br>Ground floor - left wing, Office no. 4<br><br>Every working day, without prior scheduling, from 8.00 AM to 4.00 PM</p>
				</div>
				<div id='mapkit-8288'><a href="contact.php"><img src="../sr/images/naslovna/mapa-slika.jpg" alt="mapa"></a>
				</div>
			</div>
			<p style="clear: both;"><a class="zatvori" data-popup-close="popup-1" href="#">Close the window</a></p>
			<a class="popup-close" data-popup-close="popup-1" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-2" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-phone"></i>
				</div>
				<div class="phone-tekst">
					<h2>Call us on the phone!</h2>
					<p>Our telephone numbers are:<br><span style="font-weight: bold">+38121/487-41-44</span> and <span style="font-weight: bold">+38121/55-77-27</span><br>
					Call us every working day from 8.00 AM to 4.00 PM</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px; float: right; margin-top: 20px;"><a class="zatvori" data-popup-close="popup-2" href="#">Close the window</a></p>
			<a class="popup-close" data-popup-close="popup-2" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-3" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-check-square-o"></i>
				</div>
				<div class="phone-tekst">
					<h2>Fill out an on-line form!</h2>
					<p>Your complaint is forwarded directly to our electronic mail. Complaints are processed in order of their receipt, regardless of the manner of their submission.</p>
					<a class="linkbtn hvr-sweep-to-right" href="https://goo.gl/forms/Dry7eNzlpeTnV9B72" target="_blank">ONLINE FORM</a>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px; float: right; margin-top: 20px;"><a class="zatvori" data-popup-close="popup-3" href="#">Close the window</a></p>
			<a class="popup-close" data-popup-close="popup-3" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-4" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-envelope"></i>
				</div>
				<div class="phone-tekst">
					<h2>SEND YOUR COMPLAINT BY REGULAR MAIL!</h2>
					<p>You may send your complaints in any form or using <br> <a href="let-us-know.php">the form</a> we have provided.</p> <p>Our address is as follows:<br>Provincial  Protector of Citizens - Ombudsman<br>25 Mihajla Pupina Blvd.<br>21101 Novi Sad</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px; float: right; margin-top: 20px;"><a class="zatvori" data-popup-close="popup-4" href="#">Close</a></p>
			<a class="popup-close" data-popup-close="popup-4" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-5" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-at"></i>
				</div>
				<div class="phone-tekst">
					<h2>SEND YOUR COMPLAINT BY ELECTRONIC MAIL!</h2>
					<p>Complaints and attachments may be sent via electronic mail to our e-mail address: <span class="CyrLatIgnore" style="color: #ec155a">predstavke@ombudsmanapv.org</span>. Complaints are processed in order of their receipt, regardless of the manner of their submission.</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px; float: right; margin-top: 20px;"><a class="zatvori" data-popup-close="popup-5" href="#">Close</a></p>
			<a class="popup-close" data-popup-close="popup-5" href="#">x</a>
		</div>
	</div>
	<!-- End Container -->
	
	
	<!-- SLIDER REVOLUTION SCRIPT INITIALISATION -->
	<!-- LOOK THE DOCUMENTATION FOR MORE INFORMATIONS -->

	<script type="text/javascript">

		var revapi;

		jQuery(document).ready(function() {

			   revapi = jQuery('.tp-banner').revolution(
				{
					delay:12000,
					startwidth:1140,
					startheight:480,
					hideThumbs:10,
					fullWidth:"on",
					forceFullWidth:"on",
					onHoverStop:"on",
					navigationType:"none",
					soloArrowLeftHOffset:30,
					soloArrowRightHOffset:30
				});

		});

	</script>
	<!-- END REVOLUTION SLIDER -->

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<!-- <script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script> -->

	<!-- <script>
		$.CyrLatConverter('L2C');
	</script> -->

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>

<!-- Skripta za popup prozore -->
<script type="text/javascript">
	$(function() {
	//----- OPEN
	$('[data-popup-open]').on('click', function(e)  {
	var targeted_popup_class = jQuery(this).attr('data-popup-open');
	$('[data-popup="' + targeted_popup_class + '"]').fadeIn(350);
	e.preventDefault();
	});
	//----- CLOSE
	$('[data-popup-close]').on('click', function(e)  {
	var targeted_popup_class = jQuery(this).attr('data-popup-close');
	$('[data-popup="' + targeted_popup_class + '"]').fadeOut(350);
	e.preventDefault();
	});
	});
</script>

<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .vest a. Ovo se radi yato sto jenemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.vest a').addClass('vesti-slika');
	});
</script>
	

<!-- Skripta koja uzima href od jednog a elementa i daje ga drugom. Oba elementa se formiraju u CuteNews temolate i oba se nalaze pod klasom artikal zbog cega je bilo bitno da se link od kojeg se prepisuje pozicionira iznad linka kojem se daje nova vrednost  -->

<!-- Ipak ovo nije resilo problem jer se ucitavaju 4 vesti tako da onda sve cetiri slike vode ka istoj vesti. Ovo je na kraju reseno sto je u template okolo div-a u kjem se nalazi slika postavljeno [full-link]<div class="vest-sa-slikom">{short-story}</div>[/full-link]-->
<!-- <script>
	$(function() {
   		var a_href = $(this).find('.opsirnije a').attr('href');
		console.log(a_href);
		$("a.vesti-slika").attr("href", a_href);
	});
</script> -->

<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .opsirnije a. Ovo se radi zato sto je nemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.opsirnije a').addClass('hvr-sweep-to-right');
	});
</script>

<!-- javascript za prikaz taba sa strane - mouseover povecava sirinu, a mouseout vraca sirinu na prvobitnu dimenziju-->
<script>
  function changeb2b(x) {
    x.style.width = "400px";
  }

  function normalb2b(x) {
    x.style.width = "70px";
  }
</script>


</body>

</html>