<?php 
	$page = "home";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>THE PROVINCIAL PROTECTOR OF CITIZENS - OMBUDSMAN</title>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="The Provincial Protector of Citizens - Ombudsman is an independent and autonomous body of the AP Vojvodina that shall protect the rights of citizens and monitor the work of the provincial administrative authorities, public enterprises and institutions which have administrative and public competences and which were founded by the AP Vojvodina (hereinafter: Administrative authorities), as regards their actions in enacting the decisions and other legal acts of the AP Vojvodina." />

	<link rel="shortcut icon" href="../sr/images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUD3htZ3Nz_OHmAUygmFand6GDGrYu_vU&extension=.js"></script> 
	<script src="https://cdn.mapkit.io/v1/infobox.js"></script> 
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"> 
	<link href="https://cdn.mapkit.io/v1/infobox.css" rel="stylesheet" >

	<link rel="stylesheet" type="text/css" href="../sr/css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="../sr/css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="../sr/css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="../sr/css/style.css" media="screen">

	
	<script type="text/javascript" src="../sr/js/jquery.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.migrate.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="../sr/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.appear.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="../sr/js/bootstrap.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="../sr/js/plugins-scroll.js"></script>
	<script type="text/javascript" src="../sr/js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="../sr/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="../sr/js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="../sr/js/script.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "The Provincial Protector of Citizens - Ombudsman ",
	  "image" : "http://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo-en.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Bulevar Mihajla Pupina 25",
	    "addressLocality" : "Novi Sad",
	    "addressCountry" : "Serbia"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/en/index.php"
	}
	</script>

</head>
<body>

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- JavaScriptSDK za Facebook -->
	<div id="fb-root"></div>
	<script>
		(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0&appId=134142830009100&autoLogAppEvents=1';
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>

	<!-- Tab sa strane ciji link vodi ka B2B stranici  -->
	<div id="side-tab">
	  <a class="b2b" onmouseover="changeb2b(this)" onmouseout="normalb2b(this)" target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSeFZpArObbVv7yML33si_OjTKcIiAF5sk3YAZWmL4BVmn5XUQ/viewform?usp=sf_link"></a>
	</div>

	<!-- kraja taba  -->

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="../sr/index.php"><span class="CyrLatIgnore" title="Serbian language">SRB</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include_en/logo-baner.php'; ?>
				<?php include 'include_en/meni.php'; ?>
			</nav>
		</header>
		<!-- End Header -->

		<!-- slider 
			================================================== -->
		<div id="slider" class="slider1">
			<!--
			#################################
				- THEMEPUNCH BANNER -
			#################################
			-->
			
			<div class="tp-banner-container">
				<div class="tp-banner" >
					<ul>
						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="../sr/upload/slide/tastatura.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="20% 30%" data-bgrepeat="no-repeat">
							<div class="slika-effect1"></div>
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="140"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4; min-width: 500px; max-width: 500px; white-space: inherit; line-height: 55px;">КАКО ПОДНЕТИ ПРИТУЖБУ?
							</div>
							
							<!-- LAYER NR. 2 -->
							<div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div>
							
							<!-- LAYER NR. 3 -->
							<div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="obratite-nam-se.php" class="btn btn-primary">САЗНАЈТЕ ВИШЕ</a>
							</div>

							
						</li>

						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="../sr/upload/slide/odluka-slider.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="20% 30%" data-bgrepeat="no-repeat">
							<div class="slika-effect1"></div>
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="140"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4; min-width: 500px; max-width: 500px; white-space: inherit; line-height: 55px;">ШТА ЈЕ ОМБУДСМАН?
							</div>
							
							<!-- LAYER NR. 2 -->
							<div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div>
							
							<!-- LAYER NR. 3 -->
							<div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="institucija-i-postupak.php" class="btn btn-primary">САЗНАЈТЕ ВИШЕ</a>
							</div>

							
						</li>	


						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/01b.jpg"  alt="slidebg1b"  data-bgfit="cover" data-bgposition="0% 50%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Vredi li života?
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div> -->
							
							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="vredi-li-zivota.php" class="btn btn-primary">Saznajte više</a>
							</div> -->

							
						</li>
						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/02.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="0% 30%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout text-center"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Kiša menja sve!
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">Prilagodi vožnju vremenskim prilikama. 
							</div> -->

							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="340"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="kisa-menja-sve.php" class="btn btn-primary">Pročitajte više</a>
							</div> -->

							
						</li>
						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/03.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="O% 30%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Kad pijem ne vozim!
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">Koliko te košta sledeće piće? 
							</div> -->

							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="340"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="kad-pijem-ne-vozim.php" class="btn btn-primary">Saznajte više</a>
							</div> -->

							
						</li>
					</ul>
					<div class="tp-bannertimer"></div>
				</div>
			</div>
		</div>
		<!-- End slider -->

		<!-- content 
			================================================== -->
		<div class="naslovna-content" id="content">


			<!-- vesti i sidebar
				================================================== -->
			<div class="section-content services-section">

				<div class="services-box1">
					<div class="container">
						<div class="row">

							<div class="col-md-9">
								<div class="novo">
									<div class="triggerAnimation animated" data-animate="fadeInRight">
										<!-- <a href=""><img src="" alt=""></a> -->
										<?php
									        $number = 6;
									        $template = "vesti-naslovna-2";
									    	$category = "1,2,3";
									    	$PHP_SELF = 'vest-one.php';
									        include("../cnews/show_news.php");
									    ?>
									</div>

									<!-- <div class="artikal triggerAnimation animated" data-animate="fadeInRight">
										<div class="vest">
											<h4>Омбудсману похвале, студентима сертификати</h4>
											<h6 class="datum">26. децембар 2017.</h6>
											<p class="fontaccess">Зоран Павловић, покрајински заштитник грађана – омбудсман, уручио је данас студентима Факултета за правне и пословне студије „Лазар Вркатић“  сертификате о завршеној стручној пракси у области људских права. Током пет дана, колико је трајала пракса, запослени у институцији омбудсмана упознали су студенте са организацијом, надлежностима и радом Покрајинског заштитника грађана и омогућили им практичан рад на решавању притужби грађана...</p>
											<a href="vesti.php" class="hvr-sweep-to-right">Опширније...</a>
										</div>
									</div> -->									

								</div>
								
							</div>
							<div class="col-md-3 sidebar-border">
								<aside class="sidebar-advanced">

									<div class="photo-stream">

										<div class="gallery">
											<a href="ombudsman-i-zamenici.php"><img class="hvr-shrink" src="../sr/images/naslovna/ombudsman.jpg" alt="Ombudsman"/></a>
										</div>
										<h3>Проф. др Зоран Павловић <br><div class="funkcija">Покрајински заштитник грађана - омбудсман</div></h3>
									</div>

									<div class="company-info">

										<h2>Поднесите притужбу</h2>

										<p>Можете нам се обратити лично, телефоном, путем онлајн обрасца, поштом или имејлом.</p>

										<div class="social-buttons">

											<a data-popup-open="popup-1" href="#"><i class="fa fa-user hvr-float"></i></a>
											<a data-popup-open="popup-2" href="#"><i class="fa fa-phone hvr-float"></i></a>
											<a data-popup-open="popup-3" href="#"><i class="fa fa-check-square-o hvr-float"></i></a>
											<a data-popup-open="popup-4" href="#"><i class="fa fa-envelope hvr-float"></i></a>
											<a data-popup-open="popup-5" href="#"><i class="fa fa-at hvr-float"></i></a>


										</div>

									</div>

									<div class="radno-vreme">

										<h3>Радно време</h3>
										<p style="font-weight: bold">Пон-Пет: 08.00 - 16.00</p>
										<p>Булевар Михајла Пупина 25<br>Зграда Воде Војводине (Бивша ДТД)<br>21101 Нови Сад</p>
										<p><i class="fa fa-phone"></i>021/487-41-44<br><i class="fa fa-phone"></i>021/55-77-27<br><i class="fa fa-fax"></i>021/487-41-44</p>
										<p style="padding-right: 10px;" class="CyrLatIgnore"><i class="fa fa-envelope-o "></i>office@ombudsmanapv.org</p>										

									</div>

									<!-- <div class="our-newsletter">

										<h3><i class="fas fa-chart-line"></i> Our newsletter</h3>

										<form>
											<p>Subscribe to our awesome newsletter!</p>
											<input type="email" name="email" placeholder="email@example.com"/>
											<button>Subscribe</button>
										</form>

									</div>

									<div class="photo-stream">

										<h3><i class="fa fa-picture-o"></i> Photo stream</h3>

										<div class="gallery">
											<a href="#"><img src="assets/images/spice.jpg" alt="Spice"/></a>
											<a href="#"><img src="assets/images/sahale-wa.jpg" alt="Sahale-wa"/></a>

											<p class="pagination">
												<span>2 of 43</span>
												<a href="#" class="previous"></a>
												<a href="#" class="next"></a>
											</p>
										</div>
									</div> -->

								</aside>
							</div>			
						</div>
					</div>
				</div>
			
			<!-- YouTube and Facebook section ========================================================================= -->
			<?php include 'include_en/youtube-facebook-section.php'; ?>	

			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include_en/linkovi-1-section.php'; ?>

		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include_en/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- POPUP nevidljivi prozori -->

	<div class="popup" data-popup="popup-1" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div>
				<div class="popup-tekst"><h2>Поднесите притужбу лично!</h2><p>Булевар Михајла Пупина 25, Нови Сад<br>Зграда Воде Војводине (ДТД зграда)<br>Приземље-лево крило, канцеларија бр.4<br><br>Сваким радним даном, без заказивања, од 08 до 16 часова.</p>
				</div>
				<div id='mapkit-8288'><a href="#"><img src="images/naslovna/mapa-slika.jpg" alt="mapa"></a>
				</div>
			</div>
			<p style="clear: both;"><a class="zatvori" data-popup-close="popup-1" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-1" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-2" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-phone"></i>
				</div>
				<div class="phone-tekst">
					<h2>Позовите нас телефоном!</h2>
					<p>Наши бројеви телефона су:<br><span style="font-weight: bold">021/487-41-44</span> и <span style="font-weight: bold">021/55-77-27</span><br>
					Позовите нас радним даном од 08 до 16 часова.</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px";><a class="zatvori" data-popup-close="popup-2" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-2" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-3" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-check-square-o"></i>
				</div>
				<div class="phone-tekst">
					<h2>Попуните онлајн образац!</h2>
					<p>Ваша притужба се директно прослеђује на нашу електронску адресу. Притужбе се oбрaђуjу прeмa рeдoслeду приjeмa, бeз oбзирa нa нaчин њихoвoг пoднoшeњa.</p>
					<a class="linkbtn hvr-sweep-to-right" href="https://goo.gl/forms/Dry7eNzlpeTnV9B72" target="_blank">ОНЛАЈН ОБРАЗАЦ</a>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px";><a class="zatvori" data-popup-close="popup-3" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-3" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-4" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-envelope"></i>
				</div>
				<div class="phone-tekst">
					<h2>ПОШАЉИТЕ ПРИТУЖБУ ПОШТОМ!</h2>
					<p>Притужбу нам можете послати у било којем облику или користећи наш <a href="#">образац</a>.</p> <p>Наша адреса је:<br>Покрајински заштитник грађана - омбудсман<br>Булевар Михајла Пупина 25<br>21101 Нови Сад</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px";><a class="zatvori" data-popup-close="popup-4" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-4" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-5" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-at"></i>
				</div>
				<div class="phone-tekst">
					<h2>ПОШАЉИТЕ ПРИТУЖБУ ЕЛЕКТРОНСКОМ ПОШТОМ!</h2>
					<p>Притужбу и прилоге нам можете послати путем електронске поруке на нашу имејл адресу <span class="CyrLatIgnore" style="color: #ec155a">predstavke@ombudsmanapv.org</span>. Притужбе се oбрaђуjу прeмa рeдoслeду приjeмa, бeз oбзирa нa нaчин њихoвoг пoднoшeњa.</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px";><a class="zatvori" data-popup-close="popup-5" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-5" href="#">x</a>
		</div>
	</div>
	<!-- End Container -->
	
	
	<!-- SLIDER REVOLUTION SCRIPT INITIALISATION -->
	<!-- LOOK THE DOCUMENTATION FOR MORE INFORMATIONS -->

	<script type="text/javascript">

		var revapi;

		jQuery(document).ready(function() {

			   revapi = jQuery('.tp-banner').revolution(
				{
					delay:12000,
					startwidth:1140,
					startheight:480,
					hideThumbs:10,
					fullWidth:"on",
					forceFullWidth:"on",
					onHoverStop:"on",
					navigationType:"none",
					soloArrowLeftHOffset:30,
					soloArrowRightHOffset:30
				});

		});

	</script>
	<!-- END REVOLUTION SLIDER -->

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<!-- <script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script> -->

	<!-- <script>
		$.CyrLatConverter('L2C');
	</script> -->

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>

<!-- Skripta za popup prozore -->
<script type="text/javascript">
	$(function() {
	//----- OPEN
	$('[data-popup-open]').on('click', function(e)  {
	var targeted_popup_class = jQuery(this).attr('data-popup-open');
	$('[data-popup="' + targeted_popup_class + '"]').fadeIn(350);
	e.preventDefault();
	});
	//----- CLOSE
	$('[data-popup-close]').on('click', function(e)  {
	var targeted_popup_class = jQuery(this).attr('data-popup-close');
	$('[data-popup="' + targeted_popup_class + '"]').fadeOut(350);
	e.preventDefault();
	});
	});
</script>

<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .vest a. Ovo se radi yato sto jenemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.vest a').addClass('vesti-slika');
	});
</script>
	

<!-- Skripta koja uzima href od jednog a elementa i daje ga drugom. Oba elementa se formiraju u CuteNews temolate i oba se nalaze pod klasom artikal zbog cega je bilo bitno da se link od kojeg se prepisuje pozicionira iznad linka kojem se daje nova vrednost  -->

<!-- Ipak ovo nije resilo problem jer se ucitavaju 4 vesti tako da onda sve cetiri slike vode ka istoj vesti. Ovo je na kraju reseno sto je u template okolo div-a u kjem se nalazi slika postavljeno [full-link]<div class="vest-sa-slikom">{short-story}</div>[/full-link]-->
<!-- <script>
	$(function() {
   		var a_href = $(this).find('.opsirnije a').attr('href');
		console.log(a_href);
		$("a.vesti-slika").attr("href", a_href);
	});
</script> -->

<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .opsirnije a. Ovo se radi zato sto je nemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.opsirnije a').addClass('hvr-sweep-to-right');
	});
</script>

<!-- javascript za prikaz taba sa strane - mouseover povecava sirinu, a mouseout vraca sirinu na prvobitnu dimenziju-->
<script>
  function changeb2b(x) {
    x.style.width = "400px";
  }

  function normalb2b(x) {
    x.style.width = "70px";
  }
</script>


</body>

</html>