<?php 
	$page = "about-us";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>INSTITUTION AND PROCEDURE :: THE PROVINCIAL PROTECTOR OF CITIZENS - OMBUDSMAN</title>
	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="The Provincial Protector of Citizens - Ombudsman is an independent and autonomous body of the AP Vojvodina that shall protect the rights of citizens and monitor the work of the provincial administrative authorities, public enterprises and institutions which have administrative and public competences and which were founded by the AP Vojvodina, as regards their actions in enacting the decisions and other legal acts of the AP Vojvodina." />

	<link rel="shortcut icon" href="../sr/images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUD3htZ3Nz_OHmAUygmFand6GDGrYu_vU&extension=.js"></script> 
	<script src="https://cdn.mapkit.io/v1/infobox.js"></script> 
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"> 
	<link href="https://cdn.mapkit.io/v1/infobox.css" rel="stylesheet" >

	<link rel="stylesheet" type="text/css" href="../sr/css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="../sr/css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="../sr/css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="../sr/css/style.css" media="screen">

	
	<script type="text/javascript" src="../sr/js/jquery.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.migrate.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="../sr/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.appear.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="../sr/js/bootstrap.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="../sr/js/plugins-scroll.js"></script>
	<script type="text/javascript" src="../sr/js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="../sr/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="../sr/js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="../sr/js/script.js"></script>
	<script type="text/javascript" src="../sr/js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="../sr/js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "INSTITUTION AND PROCEDURE :: The Provincial Protector of Citizens - Ombudsman",
	  "image" : "http://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo-en.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Bulevar Mihajla Pupina 25",
	    "addressLocality" : "Novi Sad",
	    "addressCountry" : "Serbia"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/en/institution-and-procedure.php"
	}
	</script>

</head>
<body>

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="../sr/index.php"><span class="CyrLatIgnore" title="Serbian language">SRB</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include_en/logo-baner.php'; ?>
				<?php include 'include_en/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			<div class="section-content page-banner-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="podvuci">
								<div class="pristupacnost">
									Величина фонта:
								</div>
								<div class="resizer">
									<!-- Koriscena Jquery skripta postavljena u fajl script.js -->
									<a href="#" class="fontSizeMinus" title="Смањи фонт" style="color: #000; font-size: 0.7em; cursor: pointer;">A</a> 
									<a class="fontReset" title="Ресетуј фонт" style="color: #000; cursor: pointer;">А</a> 
									<a href="#" class="fontSizePlus" title="Повећај фонт" style="color: #000; font-size: 1.2em; cursor: pointer;">А</a>
								</div>
								<div>
									<img src="" alt="">
								</div>
							</div>
						</div>
						
					</div>
				</div>
			</div>

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-8">
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="sta-je-ombudsman">Шта је омбудсман</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Омбудсман је институција коју је шведски парламент увео 1809. године у циљу контроле извршне власти. Реч омбудсман у шведском језику означава особу која „има слуха за народ“. Први омбудсман је имао задатак да спречи да краљ и влада игноришу законе. Користио овлашћење да од извршне власти захтева извештаје о примени закона, као и овлашћење да покреће одговарајуће поступке ради утврђивања одговорности управних службеника.</p>
										<p class="fontaccess">Покрајински заштитник грађана – омбудсман је независан и самосталан орган АП Војводине који штити права грађана и врши надзор над радом покрајинских органа управе, јавних предузећа и установа које врше управна и јавна овлашћења, а чији је оснивач АП Војводина,  у вези са њиховим поступањем у извршавању одлука и других правних аката АП Војводине.</p>
										<p class="fontaccess">На основу нове Покрајинске скупштинске одлуке о покрајинском заштитнику грађана - омбудсману, покрајински заштитник грађана - омбудсман има четири заменика од којих се по један бира за области права националних мањина, права детета и равноправност полова.</p>
										<p class="fontaccess">Одлука о успостављању институције Покрајинског омбудсмана донета је у децембру 2002. Први војвођански омбудсман изабран је 24. септембра 2003, са радом је започео у јануару 2004. године. Седиште институције је у Новом Саду.</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="nadleznosti">Надлежности Покрајинског заштитника грађана - омбудсмана</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">У циљу заштите људских права Покрајински заштитник грађана - омбудсман прима и испитује представке које се односе на повреду људских права, надзире примену прописа, контролише законитост, целисходност и ефикасност поступања органа управе и истражује њихов рад. Поред тога, прати примену међународних стандарда из области људских права, прикупља информације о примени закона и других прописа из области људских права, саставља годишњи извештај о остваривању људских права, обавештава надлежне органе и ширу јавност о кршењу људских права, иницира покретање кривичних, дисциплинских и других поступака код надлежних органа у случају кршења људских права итд.</p>
										<p class="fontaccess">Основни принципи деловања омбудсмана су законитост, непристрасност, независност и правичност.</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="ko-moze-da-se-obrati">Ко може да се обрати Покрајинском заштитнику грађана - омбудсману</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Омбудсману може да се обратити свако ко сматра да му/јој је актом или радњом органа управе повређено неко људско право.</p>
										<p class="fontaccess">Омбудсману може да се обрати и наследник, старатељ или пуномоћник лица чије је право повређено.</p>
										<p class="fontaccess">У име лица које сматра да су му/јој људска права повређена, уз писмено овлашћење, може да се обрати и невладина организација, удружење грађана или друга организација.</p>
										<p class="fontaccess">И лица лишена слободе имају право да притужбу поднесу у запечаћеној коверти, а запослени у установама у којима се налазе лица лишена слободе имају обавезу да без отварања и задржавања притужбу лица лишеног слободе доставе омбудсману.</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="postupak">Поступак Покрајинског заштитника грађана - омбудсмана</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Након обраћања грађанина притужбом (лично, обичном или електронском поштом), уколико је поступање по притужби у надлежности Покрајинског заштитника грађана - омбудсмана, а притужба поднета у року од једне године од дана учињене повреде, неправилности или од доношења последњег акта у спорној ствари, Покрајински заштитник грађана - омбудсман поступа по притужби. Покрајински заштитник грађана - омбудсман обавештава о покретању поступка подносиоца и орган управе на чији се рад притужба односи, тражећи од органа управе да се у року од 15 дана од дана изјасни о наводима из притужбе.</p>
										<p class="fontaccess">Уколико подносилац притужбе то тражи, омбудсман је дужан да сачува тајност његових/њених личних података.</p>
										<p class="fontaccess">Током трајања поступка истраге омбудсман може позивати на разговор и узимати усмене или писмене изјаве и додатна објашњења од свих лица запослених у органима управе, подносиоца притужбе, сведока, вештака и других грађана који располажу информацијама о околностима случаја. Има право да тражи од органа управе све податке и обавештења, као и непосредан увид у списе, документацију и збирке података којима ови органи располажу, укључујући државну, службену, пословну и професионалну тајну. Омбудсман има слободан приступ свим просторијама у којима се обављају послови органа управе, а у било које време и без посебне најаве може посетити све здравствене установе у којима се врши обавезно психијатријско лечење.</p>
										<p class="fontaccess">Омбудсман доноси одлуку о обустави поступка, ако по завршетку истраге нађе да нема повреде људских права, нити неправилног поступања органа и ако утврди да је орган управе, на чије се поступање притужба односила, већ током истраге отклонио повреду људских права. О обустави поступка обавештава подносиоца притужбе и орган управе на чије се поступање притужба односила.</p>
										<p class="fontaccess">Ако омбудсман након завршетка истраге утврди да је повређено неко људско право или је учињена неправилност у раду, органу управе упућује мишљење, предлог или препоруку о томе како да се неправилност или њене последице отклоне. О упућеној препоруци обавештава и подносиоца представке.</p>
										<p class="fontaccess">Органи управе којима је омбудсман упутио/ла своје мишљење, предлог или препоруку, дужни су да у року од 15 дана обавесте омбудсмана о мерама које су предузели.</p>
										<p class="fontaccess">Поред тога што поступа по притужби лица које сматра да су му актом или радњом органа управе повређена људска права Покрајински заштитник грађана - омбудсман може изузетно поступити и по сопственој иницијативи на основу сазнања и других извора, ако оцени да је вероватно да постоји или је постојала повреда људских права од стране органа управе.</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="nema-pomoci">Када грађани не могу да рачунају на Покрајинског заштитника грађана - омбудсмана</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Када је грађанину потребна правна помоћ у виду састављања поднесака или заступања (пред судом или неким од органа управе), јер за то су надлежне службе бесплатне правне помоћи при општинским/градским управама и адвокати.</p>
										<p class="fontaccess">Када су незадовољни радом органа правосуђа (према Уставу судство је независно и ниједан орган није овлашћен да контролише рад судова и тужилаштава).</p>
										<p class="fontaccess">Када имају притужби на рад послодавца и проблеме радноправне природе (грађанин треба да поднесе пријаву инспекцији рада).</p>
										<p class="fontaccess">Када имају проблема са другим грађанима.</p>
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="sidebar right-menu triggerAnimation animated" data-animate="fadeInRight">
									<div class="module-right-menu">
										<ul>
											<li><a class="taraba" href="#sta-je-ombudsman">Шта је омбудсман</a></li>
											<li><a class="taraba" href="#nadleznosti" target="_blank">Надлежност</a></li>
											<li><a class="taraba" href="#ko-moze-da-se-obrati" target="_blank">Ко може да се обрати</a></li>
											<li><a class="taraba" href="#postupak" target="_blank">Поступак</a></li>
											<li><a class="taraba" href="#nema-pomoci" target="_blank">Када вам не можемо помоћи</a></li>

										</ul>
									</div>
									<div class="col-md-12 sidebar-social-resize resize-add">
										<div class="vest-social a2a_kit a2a_kit_size_32 a2a_default_style">
											<ul class="social-list">
												<li><a class="a2a_button_facebook" href="#"><i class="fa fa-facebook-official hvr-grow"></i></a></li>
												<li><a class="a2a_button_twitter" href="#"><i class="fa fa-twitter-square hvr-grow"></i></a></li>
												<li><a class="a2a_button_google_gmail" href="#"><i class="fa fa-envelope-square hvr-grow"></i></a></li>
											</ul>
											<ul class="font-sizer">
												<li><a href="#" class="fontSizeMinus" title="Смањи фонт" style="color: #000; cursor: pointer;">A-</a></li>
												<li><a class="fontReset" title="Ресетуј фонт" style="color: #000; cursor: pointer;">А</a></li>
												<li><a href="#" class="fontSizePlus" title="Повећај фонт" style="color: #000; cursor: pointer;">А+</a></li>
											</ul>
										</div>
										<script async src="https://static.addtoany.com/menu/page.js"></script>
									</div>							
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include_en/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include_en/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="../sr/js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script>

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>



</body>

</html>