<?php 
	$page = "about-us";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>THE OMBUDSMAN AND OMBUDSMAN DEPUTIES :: THE PROVINCIAL PROTECTOR OF CITIZENS - OMBUDSMAN</title>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="The Provincial Protector of Citizens - Ombudsman is an independent and autonomous body of the AP Vojvodina that shall protect the rights of citizens and monitor the work of the provincial administrative authorities, public enterprises and institutions which have administrative and public competences and which were founded by the AP Vojvodina, as regards their actions in enacting the decisions and other legal acts of the AP Vojvodina." />

	<link rel="shortcut icon" href="../sr/images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUD3htZ3Nz_OHmAUygmFand6GDGrYu_vU&extension=.js"></script> 
	<script src="https://cdn.mapkit.io/v1/infobox.js"></script> 
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"> 
	<link href="https://cdn.mapkit.io/v1/infobox.css" rel="stylesheet" >

	<link rel="stylesheet" type="text/css" href="../sr/css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="../sr/css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="../sr/css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="../sr/css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="../sr/css/style.css" media="screen">

	
	<script type="text/javascript" src="../sr/js/jquery.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.migrate.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="../sr/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.appear.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="../sr/js/bootstrap.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.colorbox.js"></script>
	
	
	<script type="text/javascript" src="../sr/js/plugins-scroll.js"></script>
	<script type="text/javascript" src="../sr/js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="../sr/js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="../sr/js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="../sr/js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="../sr/js/script.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "THE OMBUDSMAN AND OMBUDSMAN DEPUTIES :: The Provincial Protector of Citizens - Ombudsman",
	  "image" : "http://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo-en.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Bulevar Mihajla Pupina 25",
	    "addressLocality" : "Novi Sad",
	    "addressCountry" : "Serbia"
	  },
	  "url" : "https://www.ombudsmanapv.org/ombapv/en/ombudsman-and-deputies.php"
	}
	</script>

</head>
<body>

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="https://www.ombudsmanapv.org/ombapv/sr/ombudsman-i-zamenici.php"><span class="CyrLatIgnore" title="Serbian language">SRB</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include_en/logo-baner.php'; ?>
				<?php include 'include_en/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			<div class="section-content page-banner-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="podvuci">
								<div class="pristupacnost">
									Font size:
								</div>
								<div class="resizer">
									<!-- Koriscena Jquery skripta postavljena u fajl script.js -->
									<a href="#" class="fontSizeMinus" title="Decrease font" style="color: #000; font-size: 0.7em; cursor: pointer;">A</a> 
									<a class="fontReset" title="Reset font" style="color: #000; cursor: pointer;">А</a> 
									<a href="#" class="fontSizePlus" title="Increase font" style="color: #000; font-size: 1.2em; cursor: pointer;">А</a>
								</div>
								<div>
									<img src="" alt="">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row">
							<div class="col-md-12">
								<p class="fontaccess">The Provincial  Protector of Citizens - Ombudsman is elected by the Assembly of Autonomous Province of Vojvodina, by a two-third majority vote out of the total number of deputies, whereas the Ombudsman deputies are elected by a simple majority vote out of the total number of deputies, upon the Ombudsman’s proposal. Candidates for the Ombudsman may be proposed by at least 30 deputies or the Assembly Committee responsible for issues related to organisation and work of the administration.  The Ombudsman's term of office is six years. He/she may be elected to the same office twice in succession, at the most.</p>
								<p class="fontaccess">The Provincial Ombudsman has four deputies, three of whom are specialised and elected for the field national minority rights, rights of the child and gender equality, whereas one deputy is responsible for the field of general competences.  At least one of the deputies is elected from among the less represented gender and people belonging to national minorities. The Ombudsman deputy’s  term of office is six years. He/she may be elected to the same office twice in succession, at the most.</p>
							</div>
						</div>
						<div class="row sticky-parent-element">
							<div class="col-md-8">
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="../sr/images/onama/Dragana-Coric-250x250.jpg" alt=""><a class="taraba" href="#zamenica-op"><i class="fa fa-angle-double-down"></i></a></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="ombudsman">Provincial  Protector of Citizens - Ombudsman</h2>
										<h3>Dragana Ćorić, PhD</h3>
										<p class="fontaccess"></p>
										<p class="fontaccess"></p>
										<p class="fontaccess"></p>
										<p class="fontaccess"></p>
									</div>									
								</div>
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="../sr/images/onama/Jovana-Aleksic.jpg" alt=""><a class="taraba" href="#zamenik-zd"><i class="fa fa-angle-double-down"></i></a></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="zamenica-op">Deputy Provincial Protector of Citizens - Ombudsman</h2>
										<h3>Jovana Đurić</h3>
										<p class="fontaccess">Jovana Đurić was elected for Deputy Provincial Ombudsman on December 16, 2021.</p>
										<p class="fontaccess">She graduated from the Faculty of Law in Novi Sad.</p>
										<p class="fontaccess">From 2006, she worked in the District Court in Novi Sad, and after the reform of the judiciary in the High Court in Novi Sad until September 2010. After that, she worked in the company "Agroživ" a.d. Žitište in the period from 2011 to 2014.</p>
										<p class="fontaccess">From February 2016, she enrolled in the Vojvodina Bar Association and until the election for the Deputy Provincial Ombudsman, she practiced law.</p>
										<p class="fontaccess">She was born in 1984 in Novi Sad. She is married.</p>
									</div>									
								</div>
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="../sr/images/onama/Joland-Korora-250x250.jpg" alt=""><a class="taraba" href="#zamenica-rp"><i class="fa fa-angle-double-down"></i></a></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="zamenik-zd">Deputy Provincial Protector of Citizens -Ombudsman for the Rights of the Child.</h2>
										<h3>Joland Korora</h3>
										<p class="fontaccess"></p>
									</div>									
								</div>
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="../sr/images/onama/Snezana-Knezevic-250x250.jpg" alt=""><a class="taraba" href="#zamenik-nm"><i class="fa fa-angle-double-down"></i></a></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="zamenica-rp">Deputy Provincial Protector of Citizens - Ombudsman for Gender Equality</h2>
										<h3>Snežana Knežević</h3>
										<p class="fontaccess">Snežana Knežević was elected the Deputy Provincial Protector of Citizens - Ombudsman for Gender Equality on 16 June 2017.</p>
										<p class="fontaccess">She graduated from the Faculty of Law in Novi Sad and passed the bar examination in Belgrade.</p>
										<p class="fontaccess">She became a Deputy Provincial Protector of Citizens - Ombudsman after leaving the position of the Deputy Attorney of the City of Novi Sad to which she was appointed by the Assembly of the City of Novi Sad in December 2014.   She was first appointed the Deputy Public Attorney of the City of Novi Sad by the decision of the Assembly of the City of Novi Sad in 2008.</p>
										<p class="fontaccess">From 1993 until the election for the Deputy Public Attorney of the City of Novi Sad, she worked for the City Administration of the City of Novi Sad where she was in charge of expert and legal affairs in various secretariats and departments.</p>
										<p class="fontaccess">Since 1994 she has regularly attended the Kopaonik School of Natural Law, and participated in numerous consultations in the field of various law branches.</p>
										<p class="fontaccess">She was a lecturer at the ELSA Seminar within the project “HUMAN RIGHTS” “Violence against children” and holds an ELSA diploma for the outstanding contribution to the project with a lecture on “Peer violence - Aleksa’s Law”.</p>
										<p class="fontaccess">She has completed the basic training for an intermediary - mediator.</p>
										<p class="fontaccess">She was born in Senta in 1964, and lives in Novi Sad. She is married with three children.</p>
									</div>									
								</div>
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="../sr/images/onama/Mihalj-Njilas-250x250.jpg" alt=""></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="zamenik-nm">Provincial Protector of Citizens - Ombudsman Deputy for the Protection of National Minority Rights</h2>
										<h3>Mihalj Njilaš</h3>
										<p class="fontaccess"></p>
									</div>									
								</div>
								
							</div>
							<div class="col-md-4">
								<div class="sidebar right-menu triggerAnimation animated" data-animate="fadeInRight">
									<div class="module-right-menu">
										<ul>
											<li><img src="../sr/images/onama/Dragana-Coric-250x250.jpg" alt=""><a class="taraba" href="#ombudsman">Provincial Protector of Citizens - Ombudsman</a></li>
											<li><img src="../sr/images/onama/Jovana-Aleksic.jpg" alt=""><a class="taraba" href="#zamenica-op" target="_blank">Deputy Provincial Protector of Citizens - Ombudsman</a></li>
											<li><img src="../sr/images/onama/Joland-Korora-250x250.jpg" alt=""><a class="taraba" href="#zamenik-zd" target="_blank">Deputy Provincial Protector of Citizens - Ombudsman for the Rights of the Child</a></li>
											<li><img src="../sr/images/onama/Snezana-Knezevic-250x250.jpg" alt=""><a class="taraba" href="#zamenica-rp" target="_blank">Deputy Provincial Protector of Citizens - Ombudsman for Gender Equality</a></li>
											<li><img src="../sr/images/onama/Mihalj-Njilas-250x250.jpg" alt=""><a class="taraba" href="#zamenik-nm" target="_blank">Deputy Provincial Ombudsman for the Protection of National Minority Rights</a></li>

										</ul>
									</div>							
								</div>							
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include_en/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include_en/footer.php'; ?>

		<!-- End footer -->
	</div>
	<!-- End Container -->
	
	<script type="text/javascript" src="../sr/js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>


<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script>




</body>

</html>