<?php 
	$page = "dokumenti";
?>

<!doctype html>

<html lang="sr" class="no-js">

<head>
	
	<title>ИЗВЕШТАЈИ :: ПОКРАЈИНСКИ ЗАШТИТНИК ГРАЂАНА ОМБУДСМАН</title>
	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Покрајински заштитник грађана – омбудсман је независан и самосталан орган Аутономне покрајине Војводине који штити права грађана и врши надзор над радом покрајинских органа управе, јавних предузећа и установа које врше управна и јавна овлашћења, а чији је оснивач Аутономна покрајина Војводина,  у вези са њиховим поступањем у извршавању одлука и других правних аката АП Војводине." />

	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

	
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/jquery.migrate.js"></script>
	<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="js/jquery.appear.js"></script>
	<script type="text/javascript" src="js/jquery.countTo.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
	<script type="text/javascript" src="js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="js/plugins-scroll.js"></script>
	<script type="text/javascript" src="js/waypoint.min.js"></script>

	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	
	<script type="text/javascript" src="js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Покрајински заштитник грађана - омбудсман",
	  "image" : "http://sbsns.rs/sr/images/logo/ns-logo.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Булевар Михајла Пупина 25",
	    "addressLocality" : "Нови Сад",
	    "addressCountry" : "Србија"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/sr/"
	}
	</script>

</head>
<body class="CyrLatConvert">

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="#lat"><span class="CyrLatIgnore">LAT</span></a> </li>
										<li><a href="#cyr"><span class="CyrLatIgnore">ЋИР</span></a></li>
										<li><a href="#"><span class="CyrLatIgnore">ENG</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include/logo-baner.php'; ?>
				<?php include 'include/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-8">
								<div class="row akt">
									<div class="akt-naziv">
										<h3 class="akt-naziv-header">ГОДИШЊИ ИЗВЕШТАЈИ</h3>
									</div>
								</div>
								<div class="row akt">
									<div class="akt-linija">
										<h3 class="akt-linija-header"></h3>
									</div>
								</div>
								<div class="row informator">
									<div class="informator-tekst">
										<p>Годишњи извештај је документ који Покрајински заштитник грађана - омбудсман сваке године подноси скупштини АПВ. Извештај се скупштини АПВ упућује до 31. марта текуће године и односи се на претходну календарску годину. Садржај извештаја, рокови за његову израду и упућивање Скупштини АПВ, као и обавеза његовог објављивања у јавности регулисана је чланом 21 Покрајинске скупштинске одлуке о Покрајинском заштитнику грађана - омбудсману.</p>
										<p>На захтев Покрајинског заштитника грађана - омбудсмана Скупштина АПВ Годишњи извештај ставља на дневни ред једне од својих седница и расправља о њему. Скупштина на основу скупштинске расправе о Годишњем извештају Покрајинског заштитника грађана - омбудсмана може донети одређене закључке. Важно је напоменути да Скупштина не усваја нити одобрава Годишњи извештај Покрајинског заштитника грађана - омбудсмана будући да се ради о документу независне покрајинске институције у коме она износи мишљење о стању у области људских права у АП Војводини у одређеној години.</p>
									</div>
								</div>
								<div class="naslov-upitnici">
									<span>Годишњи извештаји</span>									
								</div>
								<div class="download-upitnici">
									<ul>
										<li><a href="doc/dokumenti/izvestaji/Godisnji_izvestaj_PZG-ombudsmana_2017-online.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2017. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/Godisnji_izvestaj_PZG-ombudsmana_2016.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2016. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/Godisnji_izvestaj_PZG-ombudsmana_2015.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2015. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/Godisnji_izvestaj_PZG_2014.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2014. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/Godisnji izvestaj_2013.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2013. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/Izvestaj Pokrajinskog ombudsmana za 2012.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2012. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/Izvestaj_PO_2011_Final_001.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2011. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2010.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2010. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2009.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2009. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2008.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2008. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2007.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2007. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2006.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2006. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2005.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2005. годину</a></li>
										<li><a href="doc/dokumenti/izvestaji/godisnji_izvestaj_PO_2004.pdf" target="_blank">Годишњи извештај Покрајинског заштитника грађана - омбудсмана за 2004. годину</a></li>
									</ul>
								</div>
							</div>
							<div class="col-md-4">								
								<div class="sidebar right-documents">
									<div class="najnovije-vesti-right">
										<div class="col-md-12 najnovije-vesti-modul">
											<div class="najnovije-vesti-naslov">
												<span>DOKUMENTI</span>
											</div>
											<div class="najnovije-vesti-links">
												<ul class="najnovije-vesti-lista">
													<li><a href="akt.php">Оснивачки акт</a></li>
													<li class="active"><a class="isdisabled" href="izvestaji.php">Извештаји</a></li>
													<li><a href="informator.php">Информатор о раду</a></li>
													<li><a href="upitnici.php">Упитници</a></li>
												</ul>
											</div>
										</div>
										<div class="col-md-12 sidebar-social-resize">
											<div class="vest-social a2a_kit a2a_kit_size_32 a2a_default_style">
												<ul class="social-list">
													<li><a class="a2a_button_facebook" href="#"><i class="fa fa-facebook-official hvr-grow"></i></a></li>
													<li><a class="a2a_button_twitter" href="#"><i class="fa fa-twitter-square hvr-grow"></i></a></li>
													<li><a class="a2a_button_google_gmail" href="#"><i class="fa fa-envelope-square hvr-grow"></i></a></li>
												</ul>
												<ul class="font-sizer">
													<li><a href="#" class="fontSizeMinus" title="Смањи фонт" style="color: #000; cursor: pointer;">A-</a></li>
													<li><a class="fontReset" title="Ресетуј фонт" style="color: #000; cursor: pointer;">А</a></li>
													<li><a href="#" class="fontSizePlus" title="Повећај фонт" style="color: #000; cursor: pointer;">А+</a></li>
												</ul>
											</div>
											<script async src="https://static.addtoany.com/menu/page.js"></script>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script>

<script>
	$.CyrLatConverter();
</script>

<!-- Skripta koja po ucitavanju stranice dodaje elementu .single-vest-content p klasu fontaccess. Ovo se radi zato sto bi u suprotnom korisnik koji unoisi vest morao sam ya svaki paragraf dodavati ovu klasu. SKRIPTA script.js se PRESELILA IZ HEADERA ISPOD OVE SKRIPTE JER SE U NJOJ NALAZI KOD ZA SMANJIVANJE I POVECAVANJE FONTOVA U PARAGRAFU SA KLASOM FONTACCESS. Prvo mora da se doda klasa a tek onda da se izvrsi skripta za resize fontova.-->
<script>
	$(document).ready(function() {
	  $('.single-vest-content p').addClass('fontaccess');
	});
</script>


<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .vest a. Ovo se radi yato sto jenemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.sve-vesti-vest a').addClass('sve-vesti-slika');
	});
</script>

<script type="text/javascript" src="js/script.js"></script>

<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<!-- <script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script> -->


</body>

</html>