<?php 
	$page = "dokumenti";
?>

<!-- Preuzimanje naslova vesti u promenljivu $title -->
<?php
	include_once '../cnews/cn_api.php';
	$entry = cn_api_get_entry();

	if ($entry['t']) 
	{
	     // ........
	     $header_title = $entry['t'];
	     $str = $entry['s'];
	     $rawdesc = $entry['f'];
	     
	function get_string_between($string, $start, $end){
	    $string = " ".$string;
	    $ini = strpos($string,$start);
	    if ($ini == 0) return "";
	    $ini += strlen($start);
	    $len = strpos($string,$end,$ini) - $ini;
	    return substr($string,$ini,$len);
	}

	function stripBBCode($text_to_search) {
	 $pattern = '|[[\/\!]*?[^\[\]]*?]|si';
	 $replace = '';
	 return preg_replace($pattern, $replace, $text_to_search);
	}

	$rawdesc2 = stripBBCode($rawdesc);

	$pattern = "/[a-zA-Z]*[:\/\/]*[A-Za-z0-9\-_]+\.+[A-Za-z0-9\.\/%&=\?\-_]+/i";
	$replacement = "";
	$sdesc = preg_replace($pattern, $replacement, $rawdesc2);
	$fdesc = strip_tags($sdesc);

	$image = get_string_between($str, "[img]", "[/img]");


	      $title = "<title>".$header_title."</title>\n";
	      
	} else {
	      
	       $title = "<title>COVID-19 :: ПОКРАЈИНСКИ ЗАШТИТНИК ГРАЂАНА - ОМБУДСМАН</title>\n";
	    }
 ?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<!-- Postavljanje title taga -->
	<?php echo $title ?>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Покрајински заштитник грађана – омбудсман је независан и самосталан орган Аутономне покрајине Војводине који штити права грађана и врши надзор над радом покрајинских органа управе, јавних предузећа и установа које врше управна и јавна овлашћења, а чији је оснивач Аутономна покрајина Војводина,  у вези са њиховим поступањем у извршавању одлука и других правних аката АП Војводине." />

	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

	
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/jquery.migrate.js"></script>
	<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="js/jquery.appear.js"></script>
	<script type="text/javascript" src="js/jquery.countTo.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
	<script type="text/javascript" src="js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="js/plugins-scroll.js"></script>
	<script type="text/javascript" src="js/waypoint.min.js"></script>

	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	
	<script type="text/javascript" src="js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Покрајински заштитник грађана - омбудсман",
	  "image" : "https://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Булевар Михајла Пупина 25",
	    "addressLocality" : "Нови Сад",
	    "addressCountry" : "Србија"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/sr/"
	}
	</script>

</head>
<body class="CyrLatConvert">

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="#lat"><span class="CyrLatIgnore">LAT</span></a> </li>
										<li><a href="#cyr"><span class="CyrLatIgnore">ЋИР</span></a></li>
										<li><a href="#"><span class="CyrLatIgnore">ENG</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include/logo-baner.php'; ?>
				<?php include 'include/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-8">
								<div class="row akt">
									<div class="akt-naziv">
										<h3 class="akt-naziv-header"><span class="CyrLatIgnore">COVID-19</span><br>КОРОНА ВИРУС</h3>
									</div>
								</div>
								<div class="row akt">
									<div class="akt-linija">
										<h3 class="akt-linija-header"></h3>
									</div>
								</div>
								<div class="row akt" id="kretanje">
									<div class="akt-slika triggerAnimation animated fadeInRight" data-animate="fadeInRight">
										<img class="akt-slika-img" src="../sr/images/covid-19/kretanje.jpg" alt="Ograniči svoje kretanje">
									</div>
								</div>
								<div class="row akt" id="zastiti-druge">
									<div class="akt-slika triggerAnimation animated fadeInRight" data-animate="fadeInRight">
										<img class="akt-slika-img" src="../sr/images/covid-19/zastita.jpg" alt="Zaštiti druge da se ne razbole">
									</div>
								</div>
								<div class="row akt" id="kako-se-zastititi">
									<div class="akt-slika triggerAnimation animated fadeInRight" data-animate="fadeInRight">
										<img class="akt-slika-img" src="../sr/images/covid-19/zastita-uputstvo.jpg" alt="Kako se zaštiti">
									</div>
								</div>
								<hr id="preporuke">
								<div class="deo-teksta" style="margin-top: 20px;">
									<div class="naslov-artikla">
										<h2>Препоруке за старије особе</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<h3>Шта је потребно да старије особе и особе са инвалидитетом знају о вирусу корона?</h3>
										<p class="fontaccess">Тренутно доступни подаци указују да је за старије особа вероватноћа да ће имати тежи облик болести коју узрокује вирус ЦОВИД -19 двоструко већа него за средовечне. Могуће је да је ово због промена у имуносистему које се дешавају са годинама па је одбрана од инфекција и болести тежа. За старије је такође вероватније да већ имају одређене здравствене проблеме који им отежавају борбу са болешћу и опоравак.</p>
										<p class="fontaccess">Поред тога, особе свих узраста, са или без инвалидитета, су у вишем ризику да се теже разболе од болести коју узрокује вирус ЦОВИД -19 ако већ имају озбиљније хроничне болести као што су болести срца, плућа или бубрега.</p>
										<p class="fontaccess">Смањење изложености зарази је посебно важно за особе са повишеним ризиком од компликација!</p>
										<h3>Ако сте у повишеном ризику ово су препоруке за вас:</h3>
										
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Обавезно останите код куће колико год је то могуће, ако у вашој заједници има вируса ЦОВИД-19, а поготово ако имате било какве симптоме респираторне инфекције (кашаљ, кијање, отежано дисање).</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Ако имате симптоме респираторне инфекције јавите се дежурном епидемиологу на бројеве телефона дате на крају овог документа</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Потрудите се да имате довољну количину лекова за преписану терапију за неколико недеља да би се смањила потреба за излажењем из куће.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Када сте изван куће, држите се на дистанци од особа које су болесне, ограничите блиске контакте колико год је то могуће и перите руке што чешће.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Избегавајте гужву, посебно у затвореним просторима где нема довољно проветравања.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Избегавајте путовање авионом и јавним превозом када је то могуће.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Унапред испланирајте шта ћете чинити ако се сами разболите или се разболи неко од особа на које се редовно ослањате</p>
										
										<h3>Планирање је кључно!</h3>

										<p class="fontaccess">Зараза вирусом ЦОВИД-19 може потрајати у вашем окружењу извесно време и у зависности од озбиљности заразе, здравствене власти могу примењивати различите мере да сачувају здравље становништва, умање изложеност зарази вирусом ЦОВИД-19 и успоре његово ширење. Креирање плана за вашу породицу и домаћинство може вам помоћи да заштитите своје здравље и здравље особа око себе у случају заразе у вашој заједници. Овај план треба да узме у обзир уобичајене дневне рутине вас и чланова ваше породице.</p>

										<h3>Свакодневне активности спречавања заразе и разболевања</h3>
										
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Често перите руке водом и сапуном, у трајању од најмање 20 секунди, поготово после одласка у тоалет, пре јела, као и након издувавања носа,</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Ако сапун и вода нису доступни у том тренутку, користите гел за дезинфекцију руку на бази алкохола, са најмање 60% алкохола. Ако су вам руке видљиво прљаве, увек их оперите сапуном и водом.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Избегавајте додиривање рукама својих очију, носа и уста</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Када кашљете или кијате покријте уста и нос лактом или користите папирну марамицу. Покушајте да не кашљете и не кијате у сопствене шаке јер ћете онда њима даље ширити вирус. Папирну марамицу баците у канту за ђубре. Ако кашљете и кијате у своје шаке, не додирујте ништа и одмах оперите руке сапуном и водом.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Држите дистанцу од других људи до два метра.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Избегавајте руковање.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">ЧПроветравајте своје просторије.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Избегавајте блиске контакте са особама које су болесне</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Останите код куће због своје безбедности и здравља</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Чистите и дезинфикујте предмете које често дотичете користећи уобичајена кућна средства дезинфекције или влажне марамице.</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Не препоручује се да особе које се добро осећају носе заштитне маске</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Заштитне маске треба да носе особе које имају симптоме заразе вирусом ЦОВИД-19 како би спречиле да се други заразе. Такође, коришћење заштитних маски је веома важно за здравствене раднике и особе које се старају о болесним особама, на пример члановима породице.</p>

										<h3>Симптоми заражености вирусом ЦОВИД-19</h3>

										<p class="fontaccess">Симптоми обухватају високу температуру, кашаљ и плиткије дисање. Ако вам се чини да имате симптоме, јавите се лекару. Ако имате јаче симптоме, што хитније тражите лекарску помоћ.</p>

										<h3>Ови симптоми обухватају:</h3>

										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Тешкоће са дисањем и плитко дисање</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Трајне болове или притисак у грудима</p>
										<p class="fontaccess" style="margin-left: 20px; padding-left: 5px; border-left: 3px solid #c7c7c7;">Помодрелост усана или лица</p>

										<p class="fontaccess">Препорука Министарства здравља и Института за јавно здравље је да се, у случају јачих симптома јавите дежурном епидемиологу на следеће бројеве телефона:</p>

										<h3>Министарство здравља</h3>
										<p class="fontaccess">064/89-45-235</p>

										<h3>Институт за јавно здравље Србије</h3>
										<p class="fontaccess">011/26-84-566</p>
										<p class="fontaccess">060/018-02-44</p>
										<p class="fontaccess">Ова листа не укључује све могуће симптоме па контактирајте лекара ако имате било које друге симптоме који делују озбиљно или забрињавајуће.</p>
									</div>
								</div>															
							</div>
							<div class="col-md-4">								
								<div class="sidebar right-documents">
									<div class="najnovije-vesti-right">
										<div class="col-md-12 najnovije-vesti-modul">
											<div class="najnovije-vesti-naslov">
												<span>#ОстаниКодКуће</span>
											</div>
											<div class="najnovije-vesti-links">
												<ul class="najnovije-vesti-lista">
													<li><a class="taraba" href="#kretanje">Ограничи кретање!</a></li>
													<li><a class="taraba" href="#zastiti-druge">Заштити друге</a></li>
													<li><a class="taraba" href="#kako-se-zastititi">Како се заштитити</a></li>
													<li><a class="taraba" href="#preporuke">Препоруке за старије особе</a></li>
												</ul>
											</div>
										</div>
										<div class="col-md-12 sidebar-social-resize">
											<div class="vest-social a2a_kit a2a_kit_size_32 a2a_default_style">
												<ul class="social-list">
													<li><a class="a2a_button_facebook" href="#"><i class="fa fa-facebook-official hvr-grow"></i></a></li>
													<li><a class="a2a_button_twitter" href="#"><i class="fa fa-twitter-square hvr-grow"></i></a></li>
													<li><a class="a2a_button_google_gmail" href="#"><i class="fa fa-envelope-square hvr-grow"></i></a></li>
												</ul>
												<ul class="font-sizer">
													<li><a href="#" class="fontSizeMinus" title="Смањи фонт" style="color: #000; cursor: pointer;">A-</a></li>
													<li><a class="fontReset" title="Ресетуј фонт" style="color: #000; cursor: pointer;">А</a></li>
													<li><a href="#" class="fontSizePlus" title="Повећај фонт" style="color: #000; cursor: pointer;">А+</a></li>
												</ul>
											</div>
											<script async src="https://static.addtoany.com/menu/page.js"></script>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script>

<script>
	$.CyrLatConverter();
</script>

<!-- Skripta koja po ucitavanju stranice dodaje elementu .single-vest-content p klasu fontaccess. Ovo se radi zato sto bi u suprotnom korisnik koji unoisi vest morao sam ya svaki paragraf dodavati ovu klasu. SKRIPTA script.js se PRESELILA IZ HEADERA ISPOD OVE SKRIPTE JER SE U NJOJ NALAZI KOD ZA SMANJIVANJE I POVECAVANJE FONTOVA U PARAGRAFU SA KLASOM FONTACCESS. Prvo mora da se doda klasa a tek onda da se izvrsi skripta za resize fontova.-->
<script>
	$(document).ready(function() {
	  $('.single-vest-content p').addClass('fontaccess');
	});
</script>


<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .vest a. Ovo se radi yato sto jenemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.sve-vesti-vest a').addClass('sve-vesti-slika');
	});
</script>

<script type="text/javascript" src="js/script.js"></script>

<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script>


</body>

</html>