<?php 
	$page = "naslovna";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>Покрајински заштитник грађана - омбудсман</title>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Покрајински заштитник грађана – омбудсман је независан и самосталан орган Аутономне покрајине Војводине који штити права грађана и врши надзор над радом покрајинских органа управе, јавних предузећа и установа које врше управна и јавна овлашћења, а чији је оснивач Аутономна покрајина Војводина,  у вези са њиховим поступањем у извршавању одлука и других правних аката АП Војводине." />

	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUD3htZ3Nz_OHmAUygmFand6GDGrYu_vU&extension=.js"></script> 
	<script src="https://cdn.mapkit.io/v1/infobox.js"></script> 
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"> 
	<link href="https://cdn.mapkit.io/v1/infobox.css" rel="stylesheet" >

	<link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

	
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/jquery.migrate.js"></script>
	<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="js/jquery.appear.js"></script>
	<script type="text/javascript" src="js/jquery.countTo.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
	<script type="text/javascript" src="js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="js/plugins-scroll.js"></script>
	<script type="text/javascript" src="js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="js/script.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Покрајински заштитник грађана - омбудсман",
	  "image" : "http://sbsns.rs/sr/images/logo/ns-logo.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Булевар Михајла Пупина 25",
	    "addressLocality" : "Нови Сад",
	    "addressCountry" : "Србија"
	  },
	  "url" : "http://www.ombudsmanapv.org/sr/"
	}
	</script>

</head>
<body class="CyrLatConvert">

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="#lat"><span class="CyrLatIgnore">LAT</span></a> </li>
										<li><a href="#cyr"><span class="CyrLatIgnore">ЋИР</span></a></li>
										<li><a href="#"><span class="CyrLatIgnore">ENG</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include/logo-baner.php' ?>
				<?php include 'include/meni.php' ?>
			</nav>
		</header>
		<!-- End Header -->

		<!-- slider 
			================================================== -->
		<div id="slider" class="slider1">
			<!--
			#################################
				- THEMEPUNCH BANNER -
			#################################
			-->
			
			<div class="tp-banner-container">
				<div class="tp-banner" >
					<ul>
						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="upload/slide/ombudsman01.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="20% 30%" data-bgrepeat="no-repeat">
							<div class="slika-effect1"></div>
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="140"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4; min-width: 500px; max-width: 500px; white-space: inherit; line-height: 55px;">КАКО ПОДНЕТИ ПРИТУЖБУ?
							</div>
							
							<!-- LAYER NR. 2 -->
							<div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div>
							
							<!-- LAYER NR. 3 -->
							<div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="vredi-li-zivota.php" class="btn btn-primary">САЗНАЈТЕ ВИШЕ</a>
							</div>

							
						</li>
						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/01b.jpg"  alt="slidebg1b"  data-bgfit="cover" data-bgposition="0% 50%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Vredi li života?
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div> -->
							
							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="vredi-li-zivota.php" class="btn btn-primary">Saznajte više</a>
							</div> -->

							
						</li>
						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/02.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="0% 30%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout text-center"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Kiša menja sve!
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">Prilagodi vožnju vremenskim prilikama. 
							</div> -->

							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="340"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="kisa-menja-sve.php" class="btn btn-primary">Pročitajte više</a>
							</div> -->

							
						</li>
						<!-- SLIDE  -->
						<!-- <li data-transition="fade" data-slotamount="7" data-masterspeed="500" > -->
							<!-- MAIN IMAGE -->
							<!-- <img src="upload/slide/03.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="O% 30%" data-bgrepeat="no-repeat"> -->
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Kad pijem ne vozim!
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">Koliko te košta sledeće piće? 
							</div> -->

							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="340"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="kad-pijem-ne-vozim.php" class="btn btn-primary">Saznajte više</a>
							</div> -->

							
						</li>
					</ul>
					<div class="tp-bannertimer"></div>
				</div>
			</div>
		</div>
		<!-- End slider -->

		<!-- content 
			================================================== -->
		<div class="naslovna-content" id="content">


			<!-- pristupacnost 
			================================================== -->
			<div class="section-content page-banner-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="podvuci">
								<div class="pristupacnost">
									Величина фонта:
								</div>
								<div class="resizer">
									<!-- Koriscena Jquery skripta postavljena u fajl script.js -->
									<a href="#" class="fontSizeMinus" title="Смањи фонт" style="color: #000; font-size: 0.7em; cursor: pointer;">A</a> 
									<a class="fontReset" title="Ресетуј фонт" style="color: #000; cursor: pointer;">А</a> 
									<a href="#" class="fontSizePlus" title="Повећај фонт" style="color: #000; font-size: 1.2em; cursor: pointer;">А</a>
								</div>
								<div>
									<img src="" alt="">
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="pretraga">
								<!-- SVG za formu -->
								<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
								  <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-search-11" viewBox="0 0 40 40">
								    <path d="M15.553 31.106c8.59 0 15.553-6.963 15.553-15.553S24.143 0 15.553 0 0 6.963 0 15.553s6.963 15.553 15.553 15.553zm0-3.888c6.443 0 11.665-5.222 11.665-11.665 0-6.442-5.222-11.665-11.665-11.665-6.442 0-11.665 5.223-11.665 11.665 0 6.443 5.223 11.665 11.665 11.665zM27.76 31.06c-.78-.78-.778-2.05.004-2.833l.463-.463c.783-.783 2.057-.78 2.834-.003l8.168 8.17c.782.78.78 2.05-.003 2.832l-.463.463c-.783.783-2.057.78-2.833.003l-8.17-8.167z"
								    fill-rule="evenodd" />
								  </symbol>
								  <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-clear-3" viewBox="0 0 20 20">
								    <path d="M8.114 10L.944 2.83 0 1.885 1.886 0l.943.943L10 8.113l7.17-7.17.944-.943L20 1.886l-.943.943-7.17 7.17 7.17 7.17.943.944L18.114 20l-.943-.943-7.17-7.17-7.17 7.17-.944.943L0 18.114l.943-.943L8.113 10z" fill-rule="evenodd" />
								  </symbol>
								</svg>
								<form novalidate="novalidate" onsubmit="return false;" class="searchbox sbx-custom">
								  <div role="search" class="sbx-google__wrapper">
								    <input type="search" name="search" placeholder="Претрага" autocomplete="off" required="required" class="sbx-custom__input">
								    <button type="submit" title="Претражите" class="sbx-custom__submit">
								      	<svg role="img" aria-label="Search">
								        	<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#sbx-icon-search-11"></use>
								      	</svg>
								    </button>
								    <button type="reset" title="Clear the search query." class="sbx-custom__reset">
								      	<svg role="img" aria-label="Reset">
								        	<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#sbx-icon-clear-3"></use>
								      	</svg>
								    </button>
								  </div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- vesti i sidebar
				================================================== -->
			<div class="section-content services-section">

				<div class="services-box1">
					<div class="container">
						<div class="row">

							<div class="col-md-9">
								<div class="novo">
									<div class="triggerAnimation animated" data-animate="fadeInRight">
										<!-- <a href=""><img src="" alt=""></a> -->
										<?php
									        $number = 4;
									        $template = "vesti-naslovna";
									    	$category = "1,2,3";
									        include("/home4/ombudsma/public_html/ombudsmanapv.org/ombapv/cnews/show_news.php");
									    ?>
									</div>

									<!-- <div class="artikal triggerAnimation animated" data-animate="fadeInRight">
										<div class="vest">
											<h4>Омбудсману похвале, студентима сертификати</h4>
											<h6 class="datum">26. децембар 2017.</h6>
											<p class="fontaccess">Зоран Павловић, покрајински заштитник грађана – омбудсман, уручио је данас студентима Факултета за правне и пословне студије „Лазар Вркатић“  сертификате о завршеној стручној пракси у области људских права. Током пет дана, колико је трајала пракса, запослени у институцији омбудсмана упознали су студенте са организацијом, надлежностима и радом Покрајинског заштитника грађана и омогућили им практичан рад на решавању притужби грађана...</p>
											<a href="vesti.php" class="hvr-sweep-to-right">Опширније...</a>
										</div>
									</div> -->									

								</div>
								
							</div>
							<div class="col-md-3">
								<aside class="sidebar-advanced">

									<div class="photo-stream">

										<div class="gallery">
											<a href="ombudsman-i-zamenici.php"><img class="hvr-shrink" src="images/naslovna/ombudsman.jpg" alt="Ombudsman"/></a>
										</div>
										<h3>Проф. др Зоран Павловић <br><div class="funkcija">Покрајински заштитник грађана - омбудсман</div></h3>
									</div>

									<div class="company-info">

										<h2>Поднесите притужбу</h2>

										<p>Можете нам се обратити лично, телефоном, путем онлајн обрасца, поштом или имејлом.</p>

										<div class="social-buttons">

											<a data-popup-open="popup-1" href="#"><i class="fa fa-user hvr-float"></i></a>
											<a data-popup-open="popup-2" href="#"><i class="fa fa-phone hvr-float"></i></a>
											<a data-popup-open="popup-3" href="#"><i class="fa fa-check-square-o hvr-float"></i></a>
											<a data-popup-open="popup-4" href="#"><i class="fa fa-envelope hvr-float"></i></a>
											<a data-popup-open="popup-5" href="#"><i class="fa fa-at hvr-float"></i></a>


										</div>

									</div>

									<div class="latest-blog-posts">

										<h3><i class="fa fa-pie-chart"></i>Наша истраживања</h3>

										<ul class="latest-posts">
											<li><a href="#">Дечји и омладински листови на језицима националних мањина у АП Војводини. </a><span>2017</span></li>
											<li><a href="#">Подршка ученицима са изузетним способностима у основним и средњим школама у АП Војводини. </a><span>2017</span></li>
											<li><a href="#">Примена афирмативних мера у области основног образовања Рома и Ромкиња на територији АП Војводине. </a><span>2017</span></li>
											<li><a href="#">Поступање институција у случајевима насиља у породици. </a><span>2016</span></li>
										</ul>
									</div>

									<!-- <div class="our-newsletter">

										<h3><i class="fas fa-chart-line"></i> Our newsletter</h3>

										<form>
											<p>Subscribe to our awesome newsletter!</p>
											<input type="email" name="email" placeholder="email@example.com"/>
											<button>Subscribe</button>
										</form>

									</div>

									<div class="photo-stream">

										<h3><i class="fa fa-picture-o"></i> Photo stream</h3>

										<div class="gallery">
											<a href="#"><img src="assets/images/spice.jpg" alt="Spice"/></a>
											<a href="#"><img src="assets/images/sahale-wa.jpg" alt="Sahale-wa"/></a>

											<p class="pagination">
												<span>2 of 43</span>
												<a href="#" class="previous"></a>
												<a href="#" class="next"></a>
											</p>
										</div>
									</div> -->

								</aside>
							</div>			
						</div>
					</div>
				</div>
			
			<!-- links-section ======================================================================================== -->
			<div class="section-content team-section">
				<!-- <div class="title-section title2">
					<div class="container triggerAnimation animated" data-animate="bounceIn">
						<h1>Kratak naslov</h1>
						<p>Kratak tekst ko su ova preduzeća i zašto se linkovi ka njihovim veb stranicama nalaze ovde </p>
					</div>
				</div> -->
				<div class="team-box2">
					<div class="container">
						<div class="row">
							<div class="col-md-4">
								<div class="team-post">
									<a href="#"><i class="fa fa-bar-chart big-icon hvr-float" aria-hidden="true"></i></a>
									<div class="team-content">
										<h2>ИСТРАЖИВАЊА</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<!-- <p>ЈGSP Nоvi Sаd је prеduzеćе kоје је nizоm dugоrоčnih оprеdеljеnjа usrеdsrеđеnо nа svаkоdnеvnо pоbоljšаnjе kvаlitеtа prеvоzа putnikа u grаdskоm, prigrаdskоm i mеđumеsnоm sаоbrаćајu</p> -->
										<!-- <ul class="team-social">
											<li><a class="world" href="http://www.gspns.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<li><a class="facebook" href="https://www.facebook.com/JgspNoviSad" target="_blank"><i class="icon-facebook"></i></a></li>
											<li><a class="twitter" href="https://twitter.com/JGSPNoviSad" target="_blank"><i class="icon-twitter"></i></a></li>
										</ul> -->
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="team-post">
									<a href="#"><i class="fa fa-info big-icon hvr-float" aria-hidden="true"></i></a>
									<div class="team-content">
										<h2>ИНФОРМАТОР О РАДУ</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<!-- <p>Јаvnо kоmunаlnо prеduzеćе "PUТ" Nоvi Sаd оsnоvао је Grаd Nоvi Sаd zа  pоtrеbе izgrаdnjе i оdržаvаnjа putеvа i ulicа nа tеritоriјi  Nоvоg Sаdа i prigrаdskih nаsеljа.</p> -->
										<!-- <ul class="team-social">
											<li><a class="world" href="http://www.jkpput.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<li><a class="facebook" href="https://www.facebook.com/jkpput/" target="_blank"><i class="icon-facebook"></i></a></li>
											<li><a class="twitter" href="#" target="_blank"><i class="icon-twitter"></i></a></li>
										</ul> -->
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="team-post">
									<a href="#"><i class="fa fa-file-text-o big-icon hvr-float" aria-hidden="true"></i></a>
									<div class="team-content">
										<h2>ИЗВЕШТАЈИ</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<!-- <p>Dеlаtnоst prеduzеćа je оdržаvаnjе, urеđеnjе i kоrišćеnjе pаrkingа i јаvnih gаrаžа, kао i uslugе drumskоg sаоbrаćаја.</p> -->
										<!-- <ul class="team-social">
											<li><a class="world" href="http://www.parkingns.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<li><a class="facebook" href="#" target="_blank"><i class="icon-facebook"></i></a></li>
											<li><a class="twitter" href="#" target="_blank"><i class="icon-twitter"></i></a></li>
										</ul> -->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include/footer.php' ?>

		<!-- End footer -->
	</div>

	<!-- POPUP nevidljivi prozori -->

	<div class="popup" data-popup="popup-1" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div>
				<div class="popup-tekst"><h2>Поднесите притужбу лично!</h2><p>Булевар Михајла Пупина 25, Нови Сад<br>Зграда Воде Војводине (ДТД зграда)<br>Приземље-лево крило, канцеларија бр.4<br><br>Сваким радним даном, без заказивања, од 08 до 16 часова.</p>
				</div>
				<div id='mapkit-8288'><a href="#"><img src="images/naslovna/mapa-slika.jpg" alt="mapa"></a>
				</div>
			</div>
			<p style="clear: both;"><a class="zatvori" data-popup-close="popup-1" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-1" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-2" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-phone"></i>
				</div>
				<div class="phone-tekst">
					<h2>Позовите нас телефоном!</h2>
					<p>Наши бројеви телефона су:<br><span style="font-weight: bold">021/487-41-44</span> и <span style="font-weight: bold">021/55-77-27</span><br>
					Позовите нас радним даном од 08 до 16 часова.</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px";><a class="zatvori" data-popup-close="popup-2" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-2" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-3" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-check-square-o"></i>
				</div>
				<div class="phone-tekst">
					<h2>Попуните онлајн образац!</h2>
					<p>Ваша притужба се директно прослеђује на нашу електронску адресу. Притужбе се oбрaђуjу прeмa рeдoслeду приjeмa, бeз oбзирa нa нaчин њихoвoг пoднoшeњa.</p>
					<a class="linkbtn hvr-sweep-to-right" href="https://goo.gl/forms/Dry7eNzlpeTnV9B72" target="_blank">ОНЛАЈН ОБРАЗАЦ</a>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px";><a class="zatvori" data-popup-close="popup-3" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-3" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-4" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-envelope"></i>
				</div>
				<div class="phone-tekst">
					<h2>ПОШАЉИТЕ ПРИТУЖБУ ПОШТОМ!</h2>
					<p>Притужбу нам можете послати у било којем облику или користећи наш <a href="#">образац</a>.</p> <p>Наша адреса је:<br>Покрајински заштитник грађана - омбудсман<br>Булевар Михајла Пупина 25<br>21101 Нови Сад</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px";><a class="zatvori" data-popup-close="popup-4" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-4" href="#">x</a>
		</div>
	</div>

	<div class="popup" data-popup="popup-5" style="display: none; z-index: 1050;">
		<div class="popup-inner">
			<div class="sadrzaj">
				<div class="popup-icon">
					<i class="fa fa-at"></i>
				</div>
				<div class="phone-tekst">
					<h2>ПОШАЉИТЕ ПРИТУЖБУ ЕЛЕКТРОНСКОМ ПОШТОМ!</h2>
					<p>Притужбу и прилоге нам можете послати путем електронске поруке на нашу имејл адресу <span class="CyrLatIgnore" style="color: #ec155a">predstavke@ombudsmanapv.org</span>. Притужбе се oбрaђуjу прeмa рeдoслeду приjeмa, бeз oбзирa нa нaчин њихoвoг пoднoшeњa.</p>
				</div>
			</div>
			<p style="clear: both; margin-bottom: 0px";><a class="zatvori" data-popup-close="popup-5" href="#">Затвори прозор</a></p>
			<a class="popup-close" data-popup-close="popup-5" href="#">x</a>
		</div>
	</div>
	<!-- End Container -->
	
	
	<!-- SLIDER REVOLUTION SCRIPT INITIALISATION -->
	<!-- LOOK THE DOCUMENTATION FOR MORE INFORMATIONS -->

	<script type="text/javascript">

		var revapi;

		jQuery(document).ready(function() {

			   revapi = jQuery('.tp-banner').revolution(
				{
					delay:12000,
					startwidth:1140,
					startheight:480,
					hideThumbs:10,
					fullWidth:"on",
					forceFullWidth:"on",
					onHoverStop:"on",
					navigationType:"none",
					soloArrowLeftHOffset:30,
					soloArrowRightHOffset:30
				});

		});

	</script>
	<!-- END REVOLUTION SLIDER -->

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script>

<script>
	$.CyrLatConverter('L2C');
</script>

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>

<!-- Skripta za popup prozore -->
<script type="text/javascript">
	$(function() {
	//----- OPEN
	$('[data-popup-open]').on('click', function(e)  {
	var targeted_popup_class = jQuery(this).attr('data-popup-open');
	$('[data-popup="' + targeted_popup_class + '"]').fadeIn(350);
	e.preventDefault();
	});
	//----- CLOSE
	$('[data-popup-close]').on('click', function(e)  {
	var targeted_popup_class = jQuery(this).attr('data-popup-close');
	$('[data-popup="' + targeted_popup_class + '"]').fadeOut(350);
	e.preventDefault();
	});
	});
</script>

<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .vest a. Ovo se radi yato sto jenemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.vest a').addClass('hvr-sweep-to-right');
	});
</script>


</body>

</html>