<?php 
	$page = "postupci";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>Покрајински заштитник грађана - омбудсман ::: Најчешће постављана питаља</title>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Покрајински заштитник грађана – омбудсман је независан и самосталан орган Аутономне покрајине Војводине који штити права грађана и врши надзор над радом покрајинских органа управе, јавних предузећа и установа које врше управна и јавна овлашћења, а чији је оснивач Аутономна покрајина Војводина,  у вези са њиховим поступањем у извршавању одлука и других правних аката АП Војводине." />

	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUD3htZ3Nz_OHmAUygmFand6GDGrYu_vU&extension=.js"></script> 
	<!-- <script src="https://cdn.mapkit.io/v1/infobox.js"></script> --> 
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"> 
	<!-- <link href="https://cdn.mapkit.io/v1/infobox.css" rel="stylesheet" > -->

	<link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

	
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/jquery.migrate.js"></script>
	<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="js/jquery.appear.js"></script>
	<script type="text/javascript" src="js/jquery.countTo.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
	<script type="text/javascript" src="js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="js/plugins-scroll.js"></script>
	<script type="text/javascript" src="js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="js/script.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Покрајински заштитник грађана - омбудсман",
	  "image" : "http://sbsns.rs/sr/images/logo/ns-logo.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Булевар Михајла Пупина 25",
	    "addressLocality" : "Нови Сад",
	    "addressCountry" : "Србија"
	  },
	  "url" : "http://www.ombudsmanapv.org/sr/"
	}
	</script>

</head>
<body class="CyrLatConvert">

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="#lat"><span class="CyrLatIgnore">LAT</span></a> </li>
										<li><a href="#cyr"><span class="CyrLatIgnore">ЋИР</span></a></li>
										<li><a href="#"><span class="CyrLatIgnore">ENG</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include/logo-baner.php'; ?>
				<?php include 'include/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			<div class="section-content page-banner-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="podvuci">
								<div class="pristupacnost">
									Величина фонта:
								</div>
								<div class="resizer">
									<!-- Koriscena Jquery skripta postavljena u fajl script.js -->
									<a href="#" class="fontSizeMinus" title="Смањи фонт" style="color: #000; font-size: 0.7em; cursor: pointer;">A</a> 
									<a class="fontReset" title="Ресетуј фонт" style="color: #000; cursor: pointer;">А</a> 
									<a href="#" class="fontSizePlus" title="Повећај фонт" style="color: #000; font-size: 1.2em; cursor: pointer;">А</a>
								</div>
								<div>
									<img src="" alt="">
								</div>
							</div>
						</div>
						
					</div>
				</div>
			</div>

			<!-- faq i sidebar
				================================================== -->
			<!-- faq section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-12">
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2 id="faq">МИШЉЕЊА И ПРЕПОРУКЕ</h2>
									</div>
									<div class="toogle-box faq-box">

										<div class="toogle-elem active">
											<div class="toogle-title">
												<h2 class="fontaccess"><a class="toogle-link" href="#"></a>29.12.2022. - ЗАШТИТА ПРАВА ДЕТЕТА</h2>
											</div>
											<div class="toogle-content">
												<p class="fontaccess">Покрајински заштитник грађана – омбудсман на основу медијских написа од 4. октобра 2022. године покренуо је поступак по сопственој иницијативи. Након спроведеног поступка и утврђених пропуста у поступању надлежних органа, <strong>Омбудсман је свим центрима за социјални рад на територији АП Војводине упутио препоруку да се у сваком случају у којем постоји сумња на насиље у породици свако дете сматра жртвом насиља, без обзира на то да ли је директно изложено насиљу, сведочи насиљу у породици или живи у породици у којој је присутно насиље и да се сходно томе примењују активности и мере заштите и подршке остваривању права детета прописане законом. У сваком случају поступка развода брака, поверавања вршења родитељског права, одређивања модела виђања детета са родитељем са којим не живи, уколико постоје сазнања о насиљу у породици, пуна заштита права и најбољих интереса детета могућа је једино кроз сагледавање целокупних околности у конкретној породици и предузимање активности и мера које обезбеђују целовиту заштиту детета.</strong></p>
												<p style="color: darkred; font-style: italic; margin-top: 10px; font-size: 0.8em;">Из Препоруке Покрајинског заштитника грађана – омбудсмана број: <span class="CyrLatIgnore">I</span>-ЗД-1-46/22б од 29. децембра 2022. године.</p>
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- banner-text1-section
				================================================== -->
			<div class="section-content banner-text2-section">
				<div class="container">
					<h1>Увек смо спремни да вас саслушамо <a href="kontakt.php">Јавите нам се</a></h1>					
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script>

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script>

<script>
	$.CyrLatConverter();
</script>

<!-- Skripta za formu -->
<!-- <script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script> -->



</body>

</html>