<?php 
	$page = "obratite";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>Покрајински заштитник грађана - омбудсман</title>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Покрајински заштитник грађана – омбудсман је независан и самосталан орган Аутономне покрајине Војводине који штити права грађана и врши надзор над радом покрајинских органа управе, јавних предузећа и установа које врше управна и јавна овлашћења, а чији је оснивач Аутономна покрајина Војводина,  у вези са њиховим поступањем у извршавању одлука и других правних аката АП Војводине." />

	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

	
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/jquery.migrate.js"></script>
	<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="js/jquery.appear.js"></script>
	<script type="text/javascript" src="js/jquery.countTo.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
	<script type="text/javascript" src="js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="js/plugins-scroll.js"></script>
	<script type="text/javascript" src="js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="js/script.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Покрајински заштитник грађана - омбудсман",
	  "image" : "http://sbsns.rs/sr/images/logo/ns-logo.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Булевар Михајла Пупина 25",
	    "addressLocality" : "Нови Сад",
	    "addressCountry" : "Србија"
	  },
	  "url" : "http://www.ombudsmanapv.org/sr/"
	}
	</script>

</head>
<body class="CyrLatConvert">

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="#lat"><span class="CyrLatIgnore">LAT</span></a> </li>
										<li><a href="#cyr"><span class="CyrLatIgnore">ЋИР</span></a></li>
										<li><a href="#"><span class="CyrLatIgnore">ENG</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include/logo-baner.php' ?>
				<?php include 'include/meni.php' ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			<div class="section-content page-banner-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="podvuci">
								<div class="pristupacnost">
									Величина фонта:
								</div>
								<div class="resizer">
									<!-- Koriscena Jquery skripta postavljena u fajl script.js -->
									<a href="#" class="fontSizeMinus" title="Смањи фонт" style="color: #000; font-size: 0.7em; cursor: pointer;">A</a> 
									<a class="fontReset" title="Ресетуј фонт" style="color: #000; cursor: pointer;">А</a> 
									<a href="#" class="fontSizePlus" title="Повећај фонт" style="color: #000; font-size: 1.2em; cursor: pointer;">А</a>
								</div>
								<div>
									<img src="" alt="">
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="pretraga">
								<!-- SVG za formu -->
								<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
								  <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-search-11" viewBox="0 0 40 40">
								    <path d="M15.553 31.106c8.59 0 15.553-6.963 15.553-15.553S24.143 0 15.553 0 0 6.963 0 15.553s6.963 15.553 15.553 15.553zm0-3.888c6.443 0 11.665-5.222 11.665-11.665 0-6.442-5.222-11.665-11.665-11.665-6.442 0-11.665 5.223-11.665 11.665 0 6.443 5.223 11.665 11.665 11.665zM27.76 31.06c-.78-.78-.778-2.05.004-2.833l.463-.463c.783-.783 2.057-.78 2.834-.003l8.168 8.17c.782.78.78 2.05-.003 2.832l-.463.463c-.783.783-2.057.78-2.833.003l-8.17-8.167z"
								    fill-rule="evenodd" />
								  </symbol>
								  <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-clear-3" viewBox="0 0 20 20">
								    <path d="M8.114 10L.944 2.83 0 1.885 1.886 0l.943.943L10 8.113l7.17-7.17.944-.943L20 1.886l-.943.943-7.17 7.17 7.17 7.17.943.944L18.114 20l-.943-.943-7.17-7.17-7.17 7.17-.944.943L0 18.114l.943-.943L8.113 10z" fill-rule="evenodd" />
								  </symbol>
								</svg>
								<form novalidate="novalidate" onsubmit="return false;" class="searchbox sbx-custom">
								  <div role="search" class="sbx-google__wrapper">
								    <input type="search" name="search" placeholder="Претрага" autocomplete="off" required="required" class="sbx-custom__input">
								    <button type="submit" title="Претражите" class="sbx-custom__submit">
								      	<svg role="img" aria-label="Search">
								        	<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#sbx-icon-search-11"></use>
								      	</svg>
								    </button>
								    <button type="reset" title="Clear the search query." class="sbx-custom__reset">
								      	<svg role="img" aria-label="Reset">
								        	<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#sbx-icon-clear-3"></use>
								      	</svg>
								    </button>
								  </div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-8">
								<div class="deo-teksta">
									<div class="naglasen-text-box">
										<p class="fontaccess">
											Покрајинском заштитнику грађана - омбудсману можете се обратити лично, телефоном, путем онлајн обрасца, поштом или имејлом. Покрајинском заштитнику грађана -  омбудсману подноси се притужба на темељу које се у институцији отвара Ваш предмет под одређеним бројем. Предмет служи као основ за даљње поступање, тј. за вођење истраге.
										</p>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="tabovi">

										<ul class="nav nav-tabs">
										  	<li class="active"><a data-toggle="tab" href="#licno"><i class="fa fa-user"></i>Лично</a></li>
										  	<li><a data-toggle="tab" href="#telefonom"><i class="fa fa-phone"></i>Телефоном</a></li>
											<li><a data-toggle="tab" href="#postom"><i class="fa fa-envelope"></i>Поштом</a></li>
										  	<li><a data-toggle="tab" href="#onlajn"><i class="fa fa-check-square-o"></i>Онлајн образац</a></li>
										  	<li><a data-toggle="tab" href="#imejl"><i class="fa fa-at"></i>Имејл</a></li>
										</ul>

										<div class="tab-content">
										  	<div id="licno" class="tab-pane fade in active">
										    	<div>
													<div class="row tab-sadrzaj">
														<div class="col-md-6">
															<h2>Поднесите притужбу лично!</h2><p class="fontaccess">Булевар Михајла Пупина 25, Нови Сад<br>Зграда Воде Војводине (ДТД зграда)<br>Приземље-лево крило, канцеларија бр.4<br><br>Сваким радним даном, без заказивања, од 08 до 16 часова.</p>
														</div>
														<div class="col-md-6">
															<div id="map"></div>
														</div>
													</div>
												</div>
											</div>
										  

										  	<div id="telefonom" class="tab-pane fade">
										    	<div>
													<div class="row tab-sadrzaj">
														<div class="col-md-12">
															<h2>Позовите нас телефоном!</h2>
															<p class="fontaccess">Сваког радног дана, од 08 до 16 часова, можете нас позвати на ове телефонске бројеве:</p>
															<h4><i class="fa fa-phone"></i>021/487-41-44<br><i class="fa fa-phone"></i>021/55-77-27<br></h4>
														</div>
													</div>
												</div>
										  	</div>
										  	<div id="postom" class="tab-pane fade">
										    	<div>
													<div class="row tab-sadrzaj">
														<div class="col-md-12">
															<h2>Пишите нам!</h2>
															<p class="fontaccess">Притужбу нам можете послати поштом у било којем облику или користећи наш <a href="#">образац</a>.</p> <p class="fontaccess">Наша адреса је:</p><p class="left-border-red-thin fontaccess">Покрајински заштитник грађана - омбудсман<br>Булевар Михајла Пупина 25<br>21101 Нови Сад</p>
														</div>
													</div>
												</div>
										  	</div>
										  	<div id="onlajn" class="tab-pane fade">
											    <div>
													<div class="row tab-sadrzaj">
														<div class="col-md-12">
															<h2>Попуните онлајн образац!</h2>
															<p class="fontaccess">Ваша притужба се директно прослеђује на нашу електронску адресу. Притужбе се oбрaђуjу прeмa рeдoслeду приjeмa, бeз oбзирa нa нaчин њихoвoг пoднoшeњa.</p>
															<a class="linkbtn hvr-sweep-to-right" href="https://goo.gl/forms/Dry7eNzlpeTnV9B72" target="_blank">ОНЛАЈН ОБРАЗАЦ</a>
														</div>
													</div>
												</div>
										  	</div>
										  	<div id="imejl" class="tab-pane fade">
											    <div>
													<div class="row tab-sadrzaj">
														<div class="col-md-12">
															<h2>Пошаљите прутужбу електронском поштом!</h2>
															<p class="fontaccess">Притужбу и прилоге, ако их има, нам можете послати путем електронске поруке на нашу имејл адресу <span class="CyrLatIgnore" style="color: #ec155a">predstavke@ombudsmanapv.org</span>. <br>Притужбе се oбрaђуjу прeмa рeдoслeду приjeмa, бeз oбзирa нa нaчин њихoвoг пoднoшeњa.</p>
														</div>
													</div>
												</div>
										  	</div>
										</div>
									</div>
								</div>
								<div class="deo-teksta">
									<div class="naslov-artikla">
										<h2>Поступак Покрајинског заштитника грађана - омбудсмана</h2>
									</div>
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess">Након обраћања грађанина притужбом (лично, обичном или електронском поштом), уколико је поступање по притужби у надлежности Покрајинског заштитника грађана - омбудсмана, а притужба поднета у року од једне године од дана учињене повреде, неправилности или од доношења последњег акта у спорној ствари, Покрајински заштитник грађана - омбудсман поступа по притужби. Покрајински заштитник грађана - омбудсман обавештава о покретању поступка подносиоца и орган управе на чији се рад притужба односи, тражећи од органа управе да се у року од 15 дана од дана изјасни о наводима из притужбе.</p>
										<p class="fontaccess">Уколико подносилац притужбе то тражи, омбудсман је дужан да сачува тајност његових/њених личних података.</p>
										<p class="fontaccess">Током трајања поступка истраге омбудсман може позивати на разговор и узимати усмене или писмене изјаве и додатна објашњења од свих лица запослених у органима управе, подносиоца притужбе, сведока, вештака и других грађана који располажу информацијама о околностима случаја. Има право да тражи од органа управе све податке и обавештења, као и непосредан увид у списе, документацију и збирке података којима ови органи располажу, укључујући државну, службену, пословну и професионалну тајну. Омбудсман има слободан приступ свим просторијама у којима се обављају послови органа управе, а у било које време и без посебне најаве може посетити све здравствене установе у којима се врши обавезно психијатријско лечење.</p>
										<p class="fontaccess">Омбудсман доноси одлуку о обустави поступка, ако по завршетку истраге нађе да нема повреде људских права, нити неправилног поступања органа и ако утврди да је орган управе, на чије се поступање притужба односила, већ током истраге отклонио повреду људских права. О обустави поступка обавештава подносиоца притужбе и орган управе на чије се поступање притужба односила.</p>
										<p class="fontaccess">Ако омбудсман након завршетка истраге утврди да је повређено неко људско право или је учињена неправилност у раду, органу управе упућује мишљење, предлог или препоруку о томе како да се неправилност или њене последице отклоне. О упућеној препоруци обавештава и подносиоца представке.</p>
										<p class="fontaccess">Органи управе којима је омбудсман упутио/ла своје мишљење, предлог или препоруку, дужни су да у року од 15 дана обавесте омбудсмана о мерама које су предузели.</p>
										<p class="fontaccess">Поред тога што поступа по притужби лица које сматра да су му актом или радњом органа управе повређена људска права Покрајински заштитник грађана - омбудсман може изузетно поступити и по сопственој иницијативи на основу сазнања и других извора, ако оцени да је вероватно да постоји или је постојала повреда људских права од стране органа управе.</p>
									</div>
								</div>															
							</div>
							<div class="col-md-4">

								
								<div class="sidebar right-documents triggerAnimation animated" data-animate="fadeInRight">
									<div class="module-right-documents">
										<div class="naslov-documents">
											ПРЕУЗМИТЕ ОБРАЗАЦ
										</div>
										<div class="images-documents">
											<div class="image1">
												<a href="#"><img class="hvr-grow" src="images/sidebar/docx.png" alt="Microsoft Word Icon"></a>
											</div>
											<div class="image2">
												<a href="#"><img class="hvr-grow" src="images/sidebar/pdf.png" alt="Adobe PDF Icon"></a>
											</div>
										</div>
										<div class="link-right">
											<ul>
												<li><a href="institucija-i-postupak.php">О омбудсману и поступку притужбе</a></li>	
											</ul>
										</div>											
									</div>
								</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- links-section ======================================================================================== -->
			<div class="section-content team-section">
				<!-- <div class="title-section title2">
					<div class="container triggerAnimation animated" data-animate="bounceIn">
						<h1>Kratak naslov</h1>
						<p>Kratak tekst ko su ova preduzeća i zašto se linkovi ka njihovim veb stranicama nalaze ovde </p>
					</div>
				</div> -->
				<div class="team-box2">
					<div class="container">
						<div class="row">
							<div class="col-md-4">
								<div class="team-post">
									<a href="#"><i class="fa fa-bar-chart big-icon hvr-float" aria-hidden="true"></i></a>
									<div class="team-content">
										<h2>ИСТРАЖИВАЊА</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<!-- <p>ЈGSP Nоvi Sаd је prеduzеćе kоје је nizоm dugоrоčnih оprеdеljеnjа usrеdsrеđеnо nа svаkоdnеvnо pоbоljšаnjе kvаlitеtа prеvоzа putnikа u grаdskоm, prigrаdskоm i mеđumеsnоm sаоbrаćајu</p> -->
										<!-- <ul class="team-social">
											<li><a class="world" href="http://www.gspns.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<li><a class="facebook" href="https://www.facebook.com/JgspNoviSad" target="_blank"><i class="icon-facebook"></i></a></li>
											<li><a class="twitter" href="https://twitter.com/JGSPNoviSad" target="_blank"><i class="icon-twitter"></i></a></li>
										</ul> -->
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="team-post">
									<a href="#"><i class="fa fa-info big-icon hvr-float" aria-hidden="true"></i></a>
									<div class="team-content">
										<h2>ИНФОРМАТОР О РАДУ</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<!-- <p>Јаvnо kоmunаlnо prеduzеćе "PUТ" Nоvi Sаd оsnоvао је Grаd Nоvi Sаd zа  pоtrеbе izgrаdnjе i оdržаvаnjа putеvа i ulicа nа tеritоriјi  Nоvоg Sаdа i prigrаdskih nаsеljа.</p> -->
										<!-- <ul class="team-social">
											<li><a class="world" href="http://www.jkpput.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<li><a class="facebook" href="https://www.facebook.com/jkpput/" target="_blank"><i class="icon-facebook"></i></a></li>
											<li><a class="twitter" href="#" target="_blank"><i class="icon-twitter"></i></a></li>
										</ul> -->
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="team-post">
									<a href="#"><i class="fa fa-file-text-o big-icon hvr-float" aria-hidden="true"></i></a>
									<div class="team-content">
										<h2>ИЗВЕШТАЈИ</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<!-- <p>Dеlаtnоst prеduzеćа je оdržаvаnjе, urеđеnjе i kоrišćеnjе pаrkingа i јаvnih gаrаžа, kао i uslugе drumskоg sаоbrаćаја.</p> -->
										<!-- <ul class="team-social">
											<li><a class="world" href="http://www.parkingns.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<li><a class="facebook" href="#" target="_blank"><i class="icon-facebook"></i></a></li>
											<li><a class="twitter" href="#" target="_blank"><i class="icon-twitter"></i></a></li>
										</ul> -->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include/footer.php' ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script>

<script>
	$.CyrLatConverter('L2C');
</script>

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>

<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<!-- <script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script> -->

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCH69OL6vjpkKbseiOwQ7P1AmFv-KBq0iU"></script>
<script src="js/map.js"></script>


</body>

</html>