<?php 
	$page = "onama";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>Покрајински заштитник грађана - омбудсман</title>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Покрајински заштитник грађана – омбудсман је независан и самосталан орган Аутономне покрајине Војводине који штити права грађана и врши надзор над радом покрајинских органа управе, јавних предузећа и установа које врше управна и јавна овлашћења, а чији је оснивач Аутономна покрајина Војводина,  у вези са њиховим поступањем у извршавању одлука и других правних аката АП Војводине." />

	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

	<!-- Skripte ccs za mapu -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUD3htZ3Nz_OHmAUygmFand6GDGrYu_vU&extension=.js"></script> 
	<script src="https://cdn.mapkit.io/v1/infobox.js"></script> 
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet"> 
	<link href="https://cdn.mapkit.io/v1/infobox.css" rel="stylesheet" >

	<link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

	
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/jquery.migrate.js"></script>
	<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="js/jquery.appear.js"></script>
	<script type="text/javascript" src="js/jquery.countTo.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
	<script type="text/javascript" src="js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="js/jquery.colorbox.js"></script>
	
	
	<script type="text/javascript" src="js/plugins-scroll.js"></script>
	<script type="text/javascript" src="js/waypoint.min.js"></script>

    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="js/jquery.mb.YTPlayer.js"></script>
	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	<script type="text/javascript" src="js/script.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Покрајински заштитник грађана - омбудсман",
	  "image" : "http://sbsns.rs/sr/images/logo/ns-logo.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Булевар Михајла Пупина 25",
	    "addressLocality" : "Нови Сад",
	    "addressCountry" : "Србија"
	  },
	  "url" : "http://www.ombudsmanapv.org/sr/"
	}
	</script>

</head>
<body class="CyrLatConvert">

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="#lat"><span class="CyrLatIgnore">LAT</span></a> </li>
										<li><a href="#cyr"><span class="CyrLatIgnore">ЋИР</span></a></li>
										<li><a href="#"><span class="CyrLatIgnore">ENG</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include/logo-baner.php'; ?>
				<?php include 'include/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			<div class="section-content page-banner-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="podvuci">
								<div class="pristupacnost">
									Величина фонта:
								</div>
								<div class="resizer">
									<!-- Koriscena Jquery skripta postavljena u fajl script.js -->
									<a href="#" class="fontSizeMinus" title="Смањи фонт" style="color: #000; font-size: 0.7em; cursor: pointer;">A</a> 
									<a class="fontReset" title="Ресетуј фонт" style="color: #000; cursor: pointer;">А</a> 
									<a href="#" class="fontSizePlus" title="Повећај фонт" style="color: #000; font-size: 1.2em; cursor: pointer;">А</a>
								</div>
								<div>
									<img src="" alt="">
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row">
							<div class="col-md-12">
								<p class="fontaccess">Покрајинског омбудсмана бира Скупштина Аутономне Покрајине Војводине двотрећинском већином гласова укупног броја посланика, док заменике омбудсмана бира простом већином гласова укупног броја посланика, на предлог омбудсмана. Кандидата за омбудсмана може предложити најмање 30 посланика или скупштински одбор надлежан за питања организације и рада управе. Мандат омбудсмана траје шест година и на исту функцију омбудсман може бити биран највише два пута узастопно.</p>
								<p class="fontaccess">Покрајински омбудсман има четири заменика, од којих три специјализована који се бирају за област права националних мањина, права детета и равноправност полова, док је један заменик задужен за област опште надлежности. Најмање по један од заменика бира се из реда мање заступљеног пола и припадника националних мањина. Мандат заменика омбудсмана траје шест година и на исту функцију заменик може бити биран највише два пута узастопно.</p>
							</div>
						</div>
						<div class="row sticky-parent-element">
							<div class="col-md-8">
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="images/onama/ombudsman.jpg" alt=""><a class="taraba" href="#zamenica-op"><i class="fa fa-angle-double-down"></i></a></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="ombudsman">Покрајински заштитник грађана - омбудсман</h2>
										<h3>Проф. др Зоран Павловић</h3>
										<p class="fontaccess">Проф. др Зоран С. Павловић је на функцију покрајинског заштитника грађана - омбудсмана ступио 1. децембра 2016. године као редовни професор и шеф Кривичноправне катедре Правног факултета за привреду и правосуђе Универзитета „Привредна академија” у Новом Саду.</p>
										<p class="fontaccess">Каријеру је започео као дипломирани правник и судијски приправник у Општинском суду у Новом Саду, да би 1991. године положио и правосудни испит. Након две године у адвокатури, осам година је био заменик Општинског јавног тужиоца у Новом Саду. Заменик новосадског Окружног јавног тужиоца постаје 2002. године, да би 2004. године постао прво Окружни јавни тужилац, а потом и руководилац Канцеларије специјалног тужиоца за организовани криминал, односно његов заменик у Новом Саду.</p>
										<p class="fontaccess">Уз учешће на бројним стручним и научним скуповима у земљи и иностранству, ангажман на пројектима Министарства правде и Министарства за науку, као и чланство у тиму за израду предлога Нацрта Закона о кривичном поступку 2006. године, током своје академске каријере објавио је више од педесет научних и стручних радова из области кривичног материјалног, кривичног процесног, међународног кривичног, међународног приватног и међународног јавног права, као и две монографије и два уџбеника у области теорије права, криминологије са виктимологијом и кричног процесног права. Члан је Хашке академије за међународно право и Виктимолошког друштва Србије.</p>
										<p class="fontaccess">Ожењен је, отац двоје деце.</p>
									</div>									
								</div>
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="images/onama/Aniko-Sirkova-small.jpg" alt=""><a class="taraba" href="#zamenik-zd"><i class="fa fa-angle-double-down"></i></a></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="zamenica-op">Заменица покрајинског заштитника грађана - омбудсмана</h2>
										<h3>Анико Ширкова</h3>
										<p class="fontaccess">Анико Ширкова је за заменицу Покрајинског омбудсмана изабрана 11. децембра 2015. године.</p>
										<p class="fontaccess">Дипломирала на Правном факултету у Новом Саду.</p>
										<p class="fontaccess">Радила је у Општинској управи општине Сента на разним административно-правним пословима до 1991. године, а након тога је била десет година запослена у бројним ранијим организационим облицима Пореске управе.</p>
										<p class="fontaccess">Децембра 2004. године постављена је за секретарку Скупштине општине Сента, а од 2008. до 2010. године била је на дужности заменика председника општине Сента, а након тога је изабрана за  председницу општине Сента.</p>
										<p class="fontaccess">Од јула 2012. године до избора за заменицу Покрајинског омбудсмана је била председница Скупштине општине Сента.</p>
										<p class="fontaccess">Рођена је 1960. године у Сенти, мајка двоје пунолетне деце.</p>
									</div>									
								</div>
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="images/onama/Milan-Dakic-250x250.jpg" alt=""><a class="taraba" href="#zamenica-rp"><i class="fa fa-angle-double-down"></i></a></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="zamenik-zd">Заменик покрајинског заштитника грађана - омбудсмана за права детета</h2>
										<h3>Милан Дакић</h3>
										<p class="fontaccess">Милан Дакић, дипломирани правник, рођен је у Београду 08. септембра 1978. године, живи у Новом Саду. Од јуна 2010. године до јуна 2017. године запослен у Покрајинском заштитнику грађана – омбудсману на радним местима стручног сарадника за међународне односе, стручног сарадника и самосталног стручног сарадника за заштиту људских права и самосталног саветника на пословима за поступање по притужбама. Учествује у раду Националног механизма за превенцију тортуре.</p>
									</div>									
								</div>
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="images/onama/Snezana-Knezevic-250x250.jpg" alt=""><a class="taraba" href="#zamenik-nm"><i class="fa fa-angle-double-down"></i></a></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="zamenica-rp">Заменица покрајинског заштитника грађана - омбудсмана за равноправност полова</h2>
										<h3>Снежана Кнежевић</h3>
										<p class="fontaccess">Снежана Кнежевић је бирана за заменицу Покрајинског заштитиника грађана - омбудсмана за равноправност полова 16. јуна 2017. године.</p>
										<p class="fontaccess">Дипломирала је на Правном факултету у Новом Саду, а правосудни испит је положила у Београду.</p>
										<p class="fontaccess">На место заменице Покрајинског заштитника грађана - омбудсмана дошла је са места заменице Правобраниоца Града Новог Сада, на коју функцију је постављена од стране Скупштине Града Новог Сада децембра 2014. године. На функцију заменице Градског јавног правобраниоца Града Новог Сада први пут је постављена одлуком Скупштине Града Новог Сада 2008. године.</p>
										<p class="fontaccess">Од 1993. године до избора за заменицу Градског јавног правобраниоца Града Новог Сада била је запослена у Градској управи града Новог Сада где је обављала стручно-правне послове у различитим секретаријатима и службама.</p>
										<p class="fontaccess">Од 1994. године је редован полазник Копаоничке школе природног права, учесник је бројних саветовања из области различитих грана права.</p>
										<p class="fontaccess">Била је предавач на И ЕЛСА семинару у оквиру пројекта <span class="CyrLatIgnore">"HUMAN RIGHTS"</span> "Насиље над децом"" и поседује ЕЛСА диплому за изузетан допринос пројекту предавањем на тему "Вршњачко насиње – Алексин закон".</p>
										<p class="fontaccess">Завршила је основну обуку за посредника-медијатора.</p>
										<p class="fontaccess">Рођена је у Сенти 1964. године, живи у Новом Саду, удата је и мајка је троје деце.</p>
									</div>									
								</div>
								<div class="ombudsman">
									<div class="col-md-4 ombudsman-slika"><img src="images/onama/Janos-Oros-250x250.jpg" alt=""></div>
									<div class="col-md-8 ombudsman-text">
										<h2 id="zamenik-nm">Заменик покрајинског заштитника грађана - омбудсмана за заштиту права националних мањина</h2>
										<h3>Јанош Орос</h3>
										<p class="fontaccess">Јанош Орос, заменик покрајинског заштитника грађана – омбудсмана за права националних мањина, изабран 12. октобра 2017. године.</p>
										<p class="fontaccess">Рођен 6. новембра 1958. године у Новом Саду од оца Мађара и мајке Словакиње.</p>
										<p class="fontaccess">Основно и средњошколско образовање завршио на мађарском језику. На новосадском Правном факултету дипломирао 1981. године. Радио у Покрајинском комитету за међународну сарадњу, а пре избора на ову функцију преко двадесет година у Покрајинском секретаријату за образовање, прописе, управу и националне мањине – националне заједнице. У четири мандата био помоћник покрајинског секретара задужен за остваривање права националних мањина.</p>
										<p class="fontaccess">Објавио више ауторских текстова на ову тему и одржао предавања у земљи и иностранству. Бави се преводилаштвом, судски тумач је за мађарски језик. Објавио Српско-мађарски и Мађарско-српски речних правних и управних термина.</p>
										<p class="fontaccess"> Говори енглески. Ожењен је, отац је једног детета и живи у Новом Саду.</p>
									</div>									
								</div>
								
							</div>
							<div class="col-md-4">
								<div class="sidebar right-menu triggerAnimation animated" data-animate="fadeInRight">
									<div class="module-right-menu">
										<ul>
											<li><img src="images/onama/ombudsman.jpg" alt=""><a class="taraba" href="#ombudsman">Покрајински заштитник грађана - омбудсман</a></li>
											<li><img src="images/onama/Aniko-Sirkova-small.jpg" alt=""><a class="taraba" href="#zamenica-op" target="_blank">Заменица омбудсмана за опште послове</a></li>
											<li><img src="images/onama/Milan-Dakic-250x250.jpg" alt=""><a class="taraba" href="#zamenik-zd" target="_blank">Заменик омбудсмана за права детета</a></li>
											<li><img src="images/onama/Snezana-Knezevic-250x250.jpg" alt=""><a class="taraba" href="#zamenica-rp" target="_blank">Заменица омбудсмана за равноправност полова</a></li>
											<li><img src="images/onama/Janos-Oros-250x250.jpg" alt=""><a class="taraba" href="#zamenik-nm" target="_blank">Заменик омбудсмана за заштиту права националних мањина</a></li>

										</ul>
									</div>							
								</div>							
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include/footer.php'; ?>

		<!-- End footer -->
	</div>
	<!-- End Container -->
	
	<script type="text/javascript" src="js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script>

<script>
	$.CyrLatConverter('L2C');
</script>

<!-- Skripta za formu -->
<script type="text/javascript">
  document.querySelector('.searchbox [type="reset"]').addEventListener('click', function() {  this.parentNode.querySelector('input').focus();});
</script>


<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script>




</body>

</html>