<?php 
	$page = "onama";
?>

<!-- Preuzimanje naslova vesti u promenljivu $title -->
<?php
	include_once '../cnews/cn_api.php';
	$entry = cn_api_get_entry();

	if ($entry['t']) 
	{
	     // ........
	     $header_title = $entry['t'];
	     $str = $entry['s'];
	     $rawdesc = $entry['f'];
	     
	function get_string_between($string, $start, $end){
	    $string = " ".$string;
	    $ini = strpos($string,$start);
	    if ($ini == 0) return "";
	    $ini += strlen($start);
	    $len = strpos($string,$end,$ini) - $ini;
	    return substr($string,$ini,$len);
	}

	function stripBBCode($text_to_search) {
	 $pattern = '|[[\/\!]*?[^\[\]]*?]|si';
	 $replace = '';
	 return preg_replace($pattern, $replace, $text_to_search);
	}

	$rawdesc2 = stripBBCode($rawdesc);

	$pattern = "/[a-zA-Z]*[:\/\/]*[A-Za-z0-9\-_]+\.+[A-Za-z0-9\.\/%&=\?\-_]+/i";
	$replacement = "";
	$sdesc = preg_replace($pattern, $replacement, $rawdesc2);
	$fdesc = strip_tags($sdesc);

	$image = get_string_between($str, "[img]", "[/img]");


	      $title = "<title>".$header_title."</title>\n";
	      
	} else {
	      
	       $title = "<title>Smernice za roditelje i škle povodom tragičnih događaja</title>\n";
	    }
 ?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<!-- Postavljanje title taga -->
	<?php echo $title ?>

	<meta charset="utf-8">
	<meta name="robots" content="noindex, nofollow" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Покрајински заштитник грађана – омбудсман је независан и самосталан орган Аутономне покрајине Војводине који штити права грађана и врши надзор над радом покрајинских органа управе, јавних предузећа и установа које врше управна и јавна овлашћења, а чији је оснивач Аутономна покрајина Војводина,  у вези са њиховим поступањем у извршавању одлука и других правних аката АП Војводине." />

	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">

	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
	<!-- <link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen"> -->	
	<!-- <link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen"> -->
	<!-- <link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen"> -->
    <!-- <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen"> -->
	<link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/hover.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen" />
	
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

	
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/jquery.migrate.js"></script>
	<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="js/jquery.appear.js"></script>
	<script type="text/javascript" src="js/jquery.countTo.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
	<script type="text/javascript" src="js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="js/plugins-scroll.js"></script>
	<script type="text/javascript" src="js/waypoint.min.js"></script>

	<!-- <link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen"> -->
	
	<script type="text/javascript" src="js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Покрајински заштитник грађана - омбудсман",
	  "image" : "https://www.ombudsmanapv.org/ombapv/sr/images/logo/ombudsman-logo.png",
	  "telephone" : [ "+381-(0)21-487-41-44", "+381-(0)21-55-77-27" ],
	  "email" : "office@ombudsmanapv.org",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Булевар Михајла Пупина 25",
	    "addressLocality" : "Нови Сад",
	    "addressCountry" : "Србија"
	  },
	  "url" : "http://www.ombudsmanapv.org/ombapv/sr/"
	}
	</script>

</head>
<body class="CyrLatConvert">

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Покрајински заштитник грађана - омбудсман</h2>
		<h3>Нови Сад</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidanja preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-9 col-sm-8">
								<span><i class="fa fa-phone-square"></i> +381-(0)21-487-41-44</span>
								<span><i class="fa fa-phone-square"></i> +381-(0)21-55-77-27</span>
								<span class="CyrLatIgnore"><i class="fa fa-at"></i> office@ombudsmanapv.org</span>
							</div>
							<div class="col-md-3 col-sm-4">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="#lat"><span class="CyrLatIgnore">LAT</span></a> </li>
										<li><a href="#cyr"><span class="CyrLatIgnore">ЋИР</span></a></li>
										<li><a href="#"><span class="CyrLatIgnore">ENG</span></a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include/logo-baner.php'; ?>
				<?php include 'include/meni.php'; ?>
			</nav>
		</header>
		
		<!-- content 
			================================================== -->
		<div class="postupak-content" id="content" style="margin-top: 46px;">


			<!-- pristupacnost 
			================================================== -->
			

			<!-- vesti i sidebar
				================================================== -->
			<!-- articles-section
				================================================== -->
			<div class="section-content articles-section">
				<div class="container">
					<div class="zivot-box">
						<div class="row sticky-parent-element-1">
							<div class="col-md-12">
								<div class="row akt">
									<div class="akt-naziv">
										<h3 class="akt-naziv-header">СМЕРНИЦЕ ЗА РОДИТЕЉЕ И ШКОЛЕ</h3>
										<h3 class="akt-naziv-header" style="font-size: 1em; margin-top: 8px;">ПОВОДОМ ТРАГИЧНИХ ДОГАЂАЈА</h3>
									</div>
								</div>
								<div class="row akt">
									<div class="akt-linija">
										<h3 class="akt-linija-header"></h3>
									</div>
								</div>
								
								<hr id="preporuke">
								<div class="deo-teksta" style="margin-top: 20px;">
									<!-- <div class="naslov-artikla">
										<h2>Дечји савет Покрајинског заштитника грађана – омбудсмана</h2>
									</div> -->
									<div class="article-content triggerAnimation animated fontaccess" data-animate="fadeInLeft">
										<p class="fontaccess"><img style="width: 100%;" src="../sr/images/smernice-2023/2023-05-06_Smernice-povodom-tragicnih-dogadjaja.jpg" alt="Smernice za roditelje i škole"></p>
										<p>Трагични догађаји који су нас потресли ових дана могу бити веома узнемирујући за велики број грађана и грађанки. Забринутост, осећај несигурности, беспомоћности, различити видови емоционалних реакција, промена у мисаоним процесима и телесним доживљајима, &nbsp;природна су реакција на овакве ситуације. Иако су недавним кризним догађајима највише погођени они који су им директно били изложени, њихове породице и најближе окружење, интензитет и последице догађаја су такви да се одражавају и могу бити угрожавајући за целокупну заједницу.</p>

										<p>Имајући у виду да се први велики трагични догађај десио у школи,&nbsp;<span style="color:#cc3366;"><strong>деца и млади су сада у посебно осетљивом положају и неопходно је да у свим контекстима у којима се деца срећу са ауторитетима имају осећај безбедности, сигурности и поверења. Зато је важно разговарати са децом на начин прилагођен узрасту и зрелости сваког детета</strong></span>.&nbsp;Улога родитеља/старатеља у разговору са децом поводом трагичних догађаја је неспорна, али је неопходно да деца осећају и знају да и у образовно-васпитним установама имају одрасле особе са којима могу да разговарају и од којих могу да затраже подршку и помоћ ако им је потребна. Разговор одраслих са децом је неопходан како би деца била у стању и могућности да своја осећања, мисли, идеје и питања обраде и организују на начин који им помаже да боље разумеју себе, ситуацију и да се осећају безбедно и сигурно.&nbsp;<span style="color:#cc3366;"><strong>Омбудсман наглашава да је у овом тренутку сарадња школе са родитељима од изузетне важности и подршка једних другима је неопходна како би сви заједно били у могућности да одговоре на потребе деце и предузимају активности и мере у најбољем интересу детета. Исто тако, неопходна је и подршка локалне заједнице, како родитељима, деци, тако и васпитно-образовним установама</strong></span>.&nbsp;Због тога је важно да будемо солидарни, да будемо упознати са начинима како да помогнемо себи и другима у превазилажењу кризне ситуације и да пружимо сву могућу помоћ и подршку коју имамо на располагању.</p>

										<p>Омбудсман је упознат са тим да је Министарство просвете свим образовно-васпитним установама упутило смернице о томе како одговорити на тренутну кризну систуацију, те&nbsp;<a href="https://prosveta.gov.rs/wp-content/uploads/2022/02/C5Psiholoske-krizne-intervencije-u-obrazovno-vaspitim-ustanovama.pdf" target="_blank">Приручник Психолошке и кризне интервенције у образовним и васпитним установама</a>.&nbsp;С тим у вези, Омбудсман позива одговорне у овим установама да следећи дате смернице и у складу са својим ресурсима, капацитетима и могућностима организују стручне тимове или други вид подршке деци, родитељима и запосленима. Међусобна комуникација, а посебно информисање родитеља и деце о планираним активностима и мерама образовно-васпитних установа важни су за стварање осећаја поверења и сигурности код њих, а&nbsp;<span style="color:#cc3366;"><strong>сарадња руководства и стручних тела образовно-васптиних установа и заједничко деловање са саветом родитеља и ученичким парламентом од изузетне су важности за планирање и предузимање адекватних, ефикасних и ефективних активности и мера у превазилажењу кризне ситуације</strong></span>.</p>

										<p>Позивајући се на наведени приручник, Омбудсман указује пре свега на то да у овој ситуацији&nbsp;<span style="font-size:18px;"><span style="color:#cc3366;"><strong>НЕ ПОМАЖЕ</strong></span></span>:</p>

										<ul>
											<li>избегавање разговора са децом о догађају</li>
											<li>прећуткивање важних и примерених информација</li>
											<li>понашање као да се ништа није догодило</li>
											<li>умањивање значаја осећања и доживљаја детета, потцењивање идеја, размишљања и питања деце</li>
											<li>поновно излагање деце трауматичном догађају (вестима, ТВ емисијама, новим информацијама о догађају, неадекватним садржајима на друштвеним мрежама и интернету у вези са догађајем и сличним ситуацијама, разговорима између одраслих о догађају у присуству деце)</li>
											<li>пожуривање опоравка</li>
											<li>потискивање својих осећања и реакција</li>
											<li>као и инсистирање на разговорима уколико детету/деци то не прија</li>
										</ul>

										<p><span style="color:#cc3366;"><strong>Деци и младима&nbsp;<span style="font-size:18px;">ПОМАЖЕ</span></strong></span>&nbsp;осећај да могу отворено са одраслима да разговарају о својим осећањима, размишљањима, да постављају питања, да могу да се изразе на различите начине (кроз писање, цртеже, игру, креативне активности), да то што нацртају, напишу не морају да поделе.</p>

										<p>Покрајински заштитник грађана &ndash; омбудсман поздравља одговор стручне заједнице на потребе друштва у кризној ситуацији и њихово ангажовање на пружању бесплатне психо-социјалне подршке свим грађанима и грађанкама, а у овом случају, посебно деци, родитељима, запосленима у просвети. Како би информације о обезбеђеним видовима подршке доспеле до што већег броја особа којима је то потребно, Омбудмсан прослеђује важне контакте и ресурсе који могу бити од користи:</p>

										<ul>
											<li>Психолошко саветовалиште &quot;ПРИЧАЈМО (К)ОД КУЋЕ&quot;: имејл: <a href="mailto:pricajmokodkuce@gmail.com"><span class="CyrLatIgnore">pricajmokodkuce@gmail.com</span></a>; чет на сајту: <a href="https://www.pricajmokodkuce.com" target="_blank"><span class="CyrLatIgnore">www.pricajmokodkuce.com</span></a>; понедељком и петком 19-21 час;</li>
											<li>Центар &quot;СРЦЕ&quot;&nbsp;&ndash; 0800-300-303; подршка путем чета на: <a href="https://www.centarsrce.org" target="_blank"><span class="CyrLatIgnore">www.centarsrce.org</span></a> сваки дан 17-23 час; имејл: <a href="mailto:vanja@centarsrce.org"><span class="CyrLatIgnore">vanja@centarsrce.org</span></a> (сваки дан);</li>
											<li>Национална дечја линија - НАДЕЛ - позивом на број 116 111, заказивањем онлајн саветовања или писањем путем чета на сајту <a href="https://www.116111.rs" target="_blank"><span class="CyrLatIgnore">https://www.116111.rs</span>/</a>; саветодавни телефон за родитеље 0800 007 000;</li>
											<li><a href="https://svejeok.rs" target="_blank"><span class="CyrLatIgnore">Svejeok.rs</span></a> - заказивањем онлајн саветовања или писањем путем чета на сајту <a href="https://svejeok.rs" target="_blank"><span class="CyrLatIgnore">https://svejeok.rs/</span></a>;</li>
											<li>Институт за ментално здравље - позивом на 063/868-1757 или 063/868-2217. Линије раде од 08-20 часова;</li>
											<li>Клиника за психијатрију УКЦС - позивом на број 066/830-0854 и заказивањем сеансе позивом на 011/366-2124 и 063/310-723;</li>
											<li>Министарство просвете - позивом на 0800 200 201 од 8-15:30 часова или имејлом на адресу: <a href="mailto:zastitaodnasilja@prosveta.gov.rs"><span class="CyrLatIgnore">zastitaodnasilja@prosveta.gov.rs</span></a>.</li>
											<li>Институт за ментално здравље: 063 8681 757 и 063 8682 217</li>
											<li>Саветодавни телефон за родитеље: 0800 007 000</li>
											<li>Центар за ментално здравље (Теразије 3): 011 361 2467</li>
											<li>Покрет Несаломиви: 0800 001 002</li>
										</ul>

										<p>Савети и смернице о томе како разговарати са децом о трагичном догађају:</p>

										<ul>
											<li>Савети Тима стручњака Института за ментално здравље како разговарати о трагичном догађају са својом децом: <a href="https://imh.org.rs/news.php?id=256" target="_blank"><span class="CyrLatIgnore">https://imh.org.rs/news.php?id=256</span></a></li>
											<li>Смернице за родитеље Одељења Филозофског факулета у Београду: Како разговарати са децом о кризним ситуацијама: <a href="https://psychosocialinnovation.net/wp-content/uploads/2023/05/Smernice-za-roditelje.pdf" target="_blank"><span class="CyrLatIgnore">https://psychosocialinnovation.net/wp-content/uploads/2023/05/Smernice-za-roditelje.pdf</span></a></li>
											<li>Портал &bdquo;Бебац&ldquo;: <a href="https://www.bebac.com/vesti/kako-razgovarati-sa-decom-o-pucnjavi-u-skoli" target="_blank"><span class="CyrLatIgnore">https://www.bebac.com/vesti/kako-razgovarati-sa-decom-o-pucnjavi-u-skoli</span></a></li>
										</ul>
									</div>
								</div>														
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<!-- linkovi-1-section
				================================================== -->
			<?php include 'include/linkovi-1-section.php'; ?>
		</div>

		<!-- footer 
			================================================== -->
		<?php include 'include/footer.php'; ?>

		<!-- End footer -->
	</div>

	<!-- End Container -->
	
	<script type="text/javascript" src="js/jquery.sticky-kit.js"></script>

	<!-- SKRIPTA ZA LEPLJENJE SIDEBAR ELEMENTA ILI NEKOG DRUGOG ELEMENTA NA STRANICI. KORISTI SE UZ FAJL jquery.sticky-kit.js koji smo pozvali u gornjoj liniji  -->
	<script>
		$(window).load(function(){
			  /*!
			 * Sticky-kit
			 * A jQuery plugin for making smart sticky elements
			 *
			 * Source: http://leafo.net/sticky-kit/
			 */
			 
			 //Ovaj deo bira element sa klasom .sidebar i mora da se doda parent element inace nece da radi
			$('.sidebar').stick_in_parent({
				parent: '.sticky-parent-element-1',
				offset_top: 250
			});

			//Ovaj deo skripte omogucava da element ne nestane kada dodje do dna parent elementa, vec tu onda krece normalno na gore sa stranicom	
			$('.sidebar')
			.on('sticky_kit:bottom', function(e) {
			    $(this).parent().css('position', 'static');
			})
			.on('sticky_kit:unbottom', function(e) {
			    $(this).parent().css('position', 'relative');
			})
		});
	</script>

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script>

<script>
	$.CyrLatConverter();
</script>

<!-- Skripta koja po ucitavanju stranice dodaje elementu .single-vest-content p klasu fontaccess. Ovo se radi zato sto bi u suprotnom korisnik koji unoisi vest morao sam ya svaki paragraf dodavati ovu klasu. SKRIPTA script.js se PRESELILA IZ HEADERA ISPOD OVE SKRIPTE JER SE U NJOJ NALAZI KOD ZA SMANJIVANJE I POVECAVANJE FONTOVA U PARAGRAFU SA KLASOM FONTACCESS. Prvo mora da se doda klasa a tek onda da se izvrsi skripta za resize fontova.-->
<script>
	$(document).ready(function() {
	  $('.single-vest-content p').addClass('fontaccess');
	});
</script>


<!-- Skripta koja po ucitavanju stranice dodaje klasu hvr-sweep-to-right elementu .vest a. Ovo se radi yato sto jenemoguce ovu klasu dodati u templejtu u CuteNews-u ([full-link]Опширније...[/full-link])-->
<script>
	$(document).ready(function() {
	  $('.sve-vesti-vest a').addClass('sve-vesti-slika');
	});
</script>

<script type="text/javascript" src="js/script.js"></script>

<!-- Skripta koja omogucava sda se link ka anchoru ne zalepi na vrh stranice vec 180px ispod vrha -->
<script>
	$(document).on('click', 'a.taraba', function(event){
	    event.preventDefault();

	    $('html, body').animate({scrollTop: $( $.attr(this, 'href') ).offset().top - 250}, 800);
	});
</script>


</body>

</html>